using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;

// Diagnose against the preserved manual-edge checkpoint before modifying anything.
public static class MMBuildingTerrainRepair20261007
{
 const string Root="Validation/BuildingTerrainRepair20261007/";
 const string Reference="Backups/BuildingTerrainRepair20261007/CanonicalReference/";
 public class Site {public Transform root;public Bounds bounds;public string name;public float raised;}
 public static Site[] Sites()=>UnityEngine.Object.FindObjectsByType<Transform>().Where(t=>t.parent&&t.parent.name.StartsWith("Architecture -")).Select(t=>{var rs=t.GetComponentsInChildren<Renderer>().Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();var b=rs.Length>0?rs[0].bounds:new Bounds(t.position,Vector3.zero);foreach(var r in rs)b.Encapsulate(r.bounds);return new Site{root=t,bounds=b,name=t.parent.parent.name+"/"+t.name};}).Where(s=>s.bounds.size.y>.3f&&s.bounds.size.x>.3f&&s.bounds.size.z>.3f).ToArray();
 static float S(float a,float b,float v)=>Mathf.SmoothStep(0,1,Mathf.InverseLerp(a,b,v));
 static float H(float[,] a,float x,float z){x=Mathf.Clamp(x,0,512);z=Mathf.Clamp(z,0,512);int ix=Mathf.Min(511,(int)x),iz=Mathf.Min(511,(int)z);return Mathf.Lerp(Mathf.Lerp(a[iz,ix],a[iz,ix+1],x-ix),Mathf.Lerp(a[iz+1,ix],a[iz+1,ix+1],x-ix),z-iz)*320-24;}
 static Dictionary<Terrain,float[,]> ReferenceHeights(Terrain[] ts){var h=new Dictionary<Terrain,float[,]>();foreach(var t in ts){var loaded=UnityEditorInternal.InternalEditorUtility.LoadSerializedFileAndForget(Reference+MMTerrainBranchContrast20261007.Key(t)+"/Terrain.asset");var d=loaded.OfType<TerrainData>().First();h[t]=d.GetHeights(0,0,513,513);foreach(var o in loaded)if(o&&!EditorUtility.IsPersistent(o))UnityEngine.Object.DestroyImmediate(o);}return h;}
 static Terrain At(Terrain[] ts,float x,float z)=>ts.FirstOrDefault(t=>x>=t.transform.position.x&&x<=t.transform.position.x+512&&z>=t.transform.position.z&&z<=t.transform.position.z+512);
 public static void Inspect(string mode){var ts=MMTerrainBranchContrast20261007.Tiles();var baseline=ReferenceHeights(ts);var sites=Sites();var lines=new List<string>();foreach(var s in sites){float worst=0;for(float z=s.bounds.min.z;z<=s.bounds.max.z;z+=1)for(float x=s.bounds.min.x;x<=s.bounds.max.x;x+=1){var t=At(ts,x,z);if(!t)continue;float before=H(baseline[t],x-t.transform.position.x,z-t.transform.position.z),now=t.SampleHeight(new Vector3(x,0,z))+t.transform.position.y;worst=Mathf.Max(worst,now-before);}s.raised=worst;lines.Add(s.name+"|"+s.bounds+"|terrainRaised="+worst);}Directory.CreateDirectory(Root+mode);File.WriteAllLines(Root+mode+"/sites_before.txt",lines);var bad=sites.Where(s=>s.raised>.25f).OrderByDescending(s=>s.raised).ToArray();Debug.Log("ARCHITECTURE_SITES="+sites.Length+" raisedSites="+bad.Length+" worst="+(bad.Length>0?bad[0].raised:0));string dir="Preview/BuildingTerrainRepair20261007/"+mode+"/Before/";Directory.CreateDirectory(dir);int i=0;foreach(var s in bad.Take(12)){CaptureSite(s,dir,"site_"+i);File.AppendAllText(Root+mode+"/capture_index.txt",i+"|"+s.name+"|"+s.bounds+"\n");i++;}}
 static void CaptureSite(Site s,string dir,string name){float size=Mathf.Max(12,Mathf.Max(s.bounds.size.x,s.bounds.size.z));var center=s.bounds.center;center.y=s.bounds.min.y+2;MMNorthAuthoredTools20261007.Capture(dir,name,center+new Vector3(-size*1.5f,size*1.4f,-size*2),center,false);}
 public static void Repair(string mode,bool realistic,bool save=false){
  var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();if(Application.isPlaying||scene.isDirty)throw new Exception("Clean Edit Mode required");if(!File.Exists(Root+mode+"/sites_before.txt"))throw new Exception("Inspect sites before editing");if(File.Exists(Root+mode+"/saved.txt"))throw new Exception("Already kept; never cumulative");
  var ts=MMTerrainBranchContrast20261007.Tiles();var baseline=ReferenceHeights(ts);var sites=Sites();var old=ts.ToDictionary(t=>t,t=>t.terrainData.GetHeights(0,0,513,513));var next=old.ToDictionary(p=>p.Key,p=>(float[,])p.Value.Clone());
  foreach(var t in ts){var p=t.transform.position;bool north=p.z==768&&p.x>=-1280&&p.x<=256;bool dragon=p.x==-1792&&p.z>=256;bool arch=p.z== -1280&&p.x>=256;
   if(!realistic){if(!north&&!dragon&&!arch)next[t]=(float[,])baseline[t].Clone();continue;}
   // New extension geometry is retained. Restore complete legacy architecture compounds,
   // including the gaps between walls, plus canonical road approaches and a wide feather.
   if(north||dragon||arch)continue;var road=MMTerrainBranchContrast20261007.Roads(t.terrainData);var near=sites.Where(s=>s.bounds.max.x+85>=p.x&&s.bounds.min.x-85<=p.x+512&&s.bounds.max.z+85>=p.z&&s.bounds.min.z-85<=p.z+512).ToArray();
   var weights=new float[513,513];for(int z=0;z<=512;z++)for(int x=0;x<=512;x++){float wx=p.x+x,wz=p.z+z,w=S(.005f,.035f,road[z,x]);foreach(var s in near){var b=s.bounds;float dx=Mathf.Max(b.min.x-wx,Mathf.Max(0,wx-b.max.x)),dz=Mathf.Max(b.min.z-wz,Mathf.Max(0,wz-b.max.z));w=Mathf.Max(w,1-S(12,82,Mathf.Sqrt(dx*dx+dz*dz)));}weights[z,x]=w;}
   // Diffuse road protection outward instead of preserving a narrow raised ribbon.
   for(int z=0;z<=512;z++)for(int x=0;x<=512;x++)if(road[z,x]>.035f)for(int dz=-30;dz<=30;dz+=2)for(int dx=-30;dx<=30;dx+=2)if(x+dx>=0&&x+dx<=512&&z+dz>=0&&z+dz<=512)weights[z+dz,x+dx]=Mathf.Max(weights[z+dz,x+dx],1-S(8,32,Mathf.Sqrt(dx*dx+dz*dz)));
   for(int z=0;z<=512;z++)for(int x=0;x<=512;x++)next[t][z,x]=Mathf.Lerp(old[t][z,x],baseline[t][z,x],weights[z,x]);
  }
  // All legacy north edges retain the user's checkpoint; only the extension side adapts.
  foreach(var n in ts.Where(t=>t.transform.position.z==768&&t.transform.position.x>=-1280&&t.transform.position.x<=256)){var south=ts.First(t=>t.transform.position==n.transform.position-new Vector3(0,0,512));for(int x=0;x<=512;x++){float delta=next[south][512,x]-next[n][0,x];for(int z=0;z<=128;z++)next[n][z,x]+=delta*(1-S(0,128,z));}}
  // Shared edges are solved from one value, including restored neighboring sites.
  foreach(var a in ts)foreach(var b in ts){var d=b.transform.position-a.transform.position;bool east=d==new Vector3(512,0,0),north=d==new Vector3(0,0,512);if(!east&&!north)continue;for(int k=0;k<=512;k++){float av=east?next[a][k,512]:next[a][512,k],bv=east?next[b][k,0]:next[b][0,k];if(Mathf.Abs(av-bv)<.000001f)continue;float value=(av+bv)*.5f;if(!realistic){bool aLegacy=a.transform.position.z<768&&a.transform.position.x> -1792&&a.transform.position.z> -1280;bool bLegacy=b.transform.position.z<768&&b.transform.position.x> -1792&&b.transform.position.z> -1280;if(aLegacy)value=av;else if(bLegacy)value=bv;}for(int i=0;i<=48;i++){float w=1-S(0,48,i);if(east){next[a][k,512-i]+=(value-av)*w;next[b][k,i]+=(value-bv)*w;}else{next[a][512-i,k]+=(value-av)*w;next[b][i,k]+=(value-bv)*w;}}}}
  var moved=new Dictionary<Transform,Vector3>();var meshes=new Dictionary<Mesh,Vector3[]>();bool kept=false;try{
   foreach(var t in ts)t.terrainData.SetHeights(0,0,next[t]);foreach(var t in ts)t.Flush();
   Func<Transform,bool> dress=t=>t.name.StartsWith("SourceTree_")||t.name.StartsWith("Eco_")||t.name.StartsWith("Rock_")||t.name.StartsWith("Bush_")||t.name.Contains("AuthoredPine_")||t.name.StartsWith("TransitionPine_")||t.name.StartsWith("ReferenceTallPine_")||t.name.StartsWith("AuthoredBoulder_")||t.name.StartsWith("DragonAuthoredBoulder_")||t.name.StartsWith("Pine_")||t.name.StartsWith("YoungPine_");
   foreach(var tr in UnityEngine.Object.FindObjectsByType<Transform>()){if(!dress(tr)||tr.GetComponentsInParent<Transform>().Skip(1).Any(dress))continue;var p=tr.position;var t=At(ts,p.x,p.z);if(!t)continue;float delta=H(next[t],p.x-t.transform.position.x,p.z-t.transform.position.z)-H(old[t],p.x-t.transform.position.x,p.z-t.transform.position.z);if(Mathf.Abs(delta)<.001f)continue;moved[tr]=p;tr.position+=Vector3.up*delta;}
   foreach(var f in UnityEngine.Object.FindObjectsByType<MeshFilter>()){if(!(f.name.StartsWith("North Alpine Rock Surface")||f.name.StartsWith("DragonRockSurface")||f.name.StartsWith("Northern World Rock "))||!f.sharedMesh||f.sharedMesh.vertexCount==0)continue;var m=f.sharedMesh;if(meshes.ContainsKey(m))continue;var v=m.vertices;meshes[m]=(Vector3[])v.Clone();for(int i=0;i<v.Length;i++){var p=f.transform.TransformPoint(v[i]);var t=At(ts,p.x,p.z);if(!t)continue;if(f.name.StartsWith("Northern World Rock "))p.y=H(next[t],p.x-t.transform.position.x,p.z-t.transform.position.z)+.055f;else p.y+=H(next[t],p.x-t.transform.position.x,p.z-t.transform.position.z)-H(old[t],p.x-t.transform.position.x,p.z-t.transform.position.z);v[i]=f.transform.InverseTransformPoint(p);}m.vertices=v;m.RecalculateNormals();m.RecalculateBounds();m.UploadMeshData(false);}
   string dir="Preview/BuildingTerrainRepair20261007/"+mode+"/After/";Directory.CreateDirectory(dir);var index=File.ReadAllLines(Root+mode+"/capture_index.txt");foreach(var line in index){var bits=line.Split('|');var s=sites.FirstOrDefault(s=>s.name==bits[1]);if(s!=null)CaptureSite(s,dir,"site_"+bits[0]);}
   if(save){foreach(var t in ts){string backup="Backups/BuildingTerrainRepair20261007/"+mode+"/"+MMTerrainBranchContrast20261007.Key(t);Directory.CreateDirectory(backup);string path=AssetDatabase.GetAssetPath(t.terrainData);if(!File.Exists(backup+"/Terrain.asset"))File.Copy(path,backup+"/Terrain.asset");EditorUtility.SetDirty(t.terrainData);AssetDatabase.SaveAssetIfDirty(t.terrainData);}foreach(var m in meshes.Keys){EditorUtility.SetDirty(m);AssetDatabase.SaveAssetIfDirty(m);}EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);File.WriteAllText(Root+mode+"/saved.txt","sites="+sites.Length+" moved="+moved.Count+" overlays="+meshes.Count);kept=true;}Debug.Log("BUILDING_REPAIR "+mode+" saved="+save+" sites="+sites.Length);
  }finally{if(!kept){foreach(var t in ts){t.terrainData.SetHeights(0,0,old[t]);t.Flush();}foreach(var p in moved)p.Key.position=p.Value;foreach(var p in meshes){p.Key.vertices=p.Value;p.Key.RecalculateNormals();p.Key.RecalculateBounds();p.Key.UploadMeshData(false);}}}
 }
}
