using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using UnityEditor.SceneManagement;
public static class MMNorthDressingFinish20261007
{
 public static void Run(bool keep=false)
 {
  var scene=SceneManager.GetActiveScene();if(scene.isDirty||scene.path!="Assets/Scenes/World/Enroth.unity")throw new Exception("Need clean Enroth");const string name="North Production Boulder Dressing 20261007";if(GameObject.Find(name))throw new Exception("Already kept");var terrains=Terrain.activeTerrains.Where(t=>t.transform.position.z==768&&t.transform.position.x>=-1280&&t.transform.position.x<768).ToArray();var dressing=UnityEngine.Object.FindObjectsByType<Transform>().Where(t=>(t.name.StartsWith("Rock_")||t.name.StartsWith("Bush_"))&&t.position.x>=-1280&&t.position.x<768&&t.position.z>=768&&t.position.z<=1280).ToArray();var states=dressing.Select(t=>System.Tuple.Create(t,t.position,t.gameObject.activeSelf)).ToArray();var root=new GameObject(name);root.hideFlags=HideFlags.HideAndDontSave;var material=new Material(Shader.Find("Standard")){name="NorthColdBoulder20261007"};material.mainTexture=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/EnvironmentAssets/UnitySamples/rock_boulder_cracked_c.png");material.color=new Color(.58f,.64f,.7f);material.SetTexture("_BumpMap",AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/EnvironmentAssets/UnitySamples/rock_boulder_cracked_n.png"));material.EnableKeyword("_NORMALMAP");material.SetFloat("_Glossiness",.15f);var meshes=new[]{"Assets/EnvironmentAssets/UnitySamples/Rock_A_01.fbx","Assets/EnvironmentAssets/UnitySamples/Rock_A_02.fbx"}.Select(p=>AssetDatabase.LoadAllAssetsAtPath(p).OfType<UnityEngine.Mesh>().First(m=>m.name.EndsWith("LOD00"))).ToArray();bool saved=false;int count=0;
  try
  {
   foreach(var tr in dressing)
   {var terrain=terrains.First(t=>tr.position.x>=t.transform.position.x&&tr.position.x<t.transform.position.x+512);float ground=MMNorthAuthoredTools20261007.Ground(terrain,tr.position.x,tr.position.z);if(ground<.5f){tr.gameObject.SetActive(false);continue;}var renderers=tr.GetComponentsInChildren<Renderer>();if(renderers.Length==0)continue;var bounds=renderers[0].bounds;foreach(var r in renderers.Skip(1))bounds.Encapsulate(r.bounds);
    if(tr.name.StartsWith("Bush_")){tr.position+=Vector3.up*(ground-bounds.min.y-.08f);continue;}
    var mesh=meshes[count%2];var boulder=new GameObject("AuthoredBoulder_"+count);boulder.transform.SetParent(root.transform,false);boulder.AddComponent<MeshFilter>().sharedMesh=mesh;var mr=boulder.AddComponent<MeshRenderer>();mr.sharedMaterial=material;float width=Mathf.Clamp(Mathf.Max(bounds.size.x,bounds.size.z),1.6f,5.5f);float scale=width/Mathf.Max(mesh.bounds.size.x,mesh.bounds.size.z);boulder.transform.localScale=Vector3.one*scale;boulder.transform.rotation=Quaternion.Euler(0,tr.eulerAngles.y+count*31.4f,0);boulder.transform.position=new Vector3(tr.position.x,ground,tr.position.z);boulder.transform.position+=Vector3.up*(ground-mr.bounds.min.y-.18f*scale);boulder.AddComponent<MeshCollider>().sharedMesh=mesh;tr.gameObject.SetActive(false);count++;
   }
   string dir="Preview/NorthAuthored20261007/ColdDressing/";Directory.CreateDirectory(dir);MMNorthAuthoredTools20261007.Capture(dir,"lake",new Vector3(-35,53,920),new Vector3(15,24,1070),false);MMNorthAuthoredTools20261007.Capture(dir,"west",new Vector3(-1050,40,910),new Vector3(-980,35,1060),false);MMNorthAuthoredTools20261007.Capture(dir,"east",new Vector3(520,45,930),new Vector3(450,35,1050),false);
   if(keep){string backup="Backups/NorthAuthored20261007/ColdDressingBefore";Directory.CreateDirectory(backup);if(!File.Exists(backup+"/Enroth.unity"))File.Copy(scene.path,backup+"/Enroth.unity");const string dirAsset="Assets/World/WorldExtensions/Generated/NorthAlpine20261007";AssetDatabase.CreateAsset(material,dirAsset+"/ColdBoulder.mat");root.hideFlags=HideFlags.None;AssetDatabase.SaveAssetIfDirty(material);EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new IOException("Save failed");saved=true;File.WriteAllText("Validation/SequentialRepair/cold_dressing_kept.txt","Replaced "+count+" northern placeholder rocks with production boulders; regrounded bushes. Accepted legacy dressing unchanged.");}
  }finally{if(!saved){foreach(var s in states){s.Item1.position=s.Item2;s.Item1.gameObject.SetActive(s.Item3);}UnityEngine.Object.DestroyImmediate(root);UnityEngine.Object.DestroyImmediate(material);}}
 }
}
