using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
public static class MMNorthIceFinish20261007
{
 const string Dir="Assets/World/WorldExtensions/Generated/NorthAlpine20261007";
 static void Clean(){var s=SceneManager.GetActiveScene();if(s.path!="Assets/Scenes/World/Enroth.unity"||s.isDirty)throw new Exception("Need clean Enroth");}
 public static void Sea(bool keep=false)
 {
  Clean();string report="Validation/SequentialRepair/sea_ice_finished.txt";if(File.Exists(report))throw new Exception("Already kept");var filters=UnityEngine.Object.FindObjectsByType<MeshFilter>().Where(f=>f.sharedMesh&&AssetDatabase.GetAssetPath(f.sharedMesh).EndsWith("_NorthFracturedIce.asset")).ToArray();if(filters.Length!=4)throw new Exception("Expected four northern ice meshes");var meshes=filters.Select(f=>f.sharedMesh).ToArray();var copies=meshes.Select(UnityEngine.Object.Instantiate).ToArray();
  try{for(int i=0;i<copies.Length;i++){copies[i].hideFlags=HideFlags.HideAndDontSave;var v=copies[i].vertices;for(int k=0;k<v.Length;k++){var p=filters[i].transform.TransformPoint(v[k]);if(p.y>.12f)p.y=.12f+(p.y-.12f)*.12f;v[k]=filters[i].transform.InverseTransformPoint(p);}copies[i].vertices=v;copies[i].RecalculateNormals();copies[i].RecalculateBounds();filters[i].sharedMesh=copies[i];}
   string dir="Preview/NorthAuthored20261007/SeaIce/";Directory.CreateDirectory(dir);MMNorthAuthoredTools20261007.Capture(dir,"shore",new Vector3(-30,26,1475),new Vector3(-30,70,1170),false);MMNorthAuthoredTools20261007.Capture(dir,"top",new Vector3(-512,850,1240),new Vector3(-512,0,1240),true);
   if(keep){string backup="Backups/NorthAuthored20261007/SeaIceBefore";Directory.CreateDirectory(backup);for(int i=0;i<meshes.Length;i++){string path=AssetDatabase.GetAssetPath(meshes[i]);if(!File.Exists(Path.Combine(backup,Path.GetFileName(path))))File.Copy(path,Path.Combine(backup,Path.GetFileName(path)));meshes[i].vertices=copies[i].vertices;meshes[i].normals=copies[i].normals;meshes[i].RecalculateBounds();EditorUtility.SetDirty(meshes[i]);AssetDatabase.SaveAssetIfDirty(meshes[i]);}File.WriteAllText(report,"Flattened four northern placeholder ice pyramids to low broken floes; horizontal footprints unchanged.");}
  }finally{for(int i=0;i<meshes.Length;i++){filters[i].sharedMesh=meshes[i];UnityEngine.Object.DestroyImmediate(copies[i]);}}
 }
 static bool InLake(Vector3 p,Vector3[] v){bool inside=false;for(int i=1,j=72;i<=72;j=i++){var a=v[j];var b=v[i];if((a.z>p.z)!=(b.z>p.z)&&p.x<(b.x-a.x)*(p.z-a.z)/(b.z-a.z)+a.x)inside=!inside;}return inside;}
 static float Channel(Vector3 p,Vector3[] v){float d=999;foreach(var r in new[]{new Vector2Int(73,29),new Vector2Int(131,25),new Vector2Int(181,23)})for(int i=0;i<r.y-1;i++){int k=r.x+i*2;var a=(v[k]+v[k+1])*.5f;var b=(v[k+2]+v[k+3])*.5f;var ab=new Vector2(b.x-a.x,b.z-a.z);float q=Mathf.Clamp01(Vector2.Dot(new Vector2(p.x-a.x,p.z-a.z),ab)/ab.sqrMagnitude);d=Mathf.Min(d,Vector2.Distance(new Vector2(p.x,p.z),new Vector2(a.x+q*ab.x,a.z+q*ab.y)));}return d;}
 public static void Lake(bool keep=false)
 {
  Clean();const string name="North Lake Broken Shore Ice 20261007";if(GameObject.Find(name))throw new Exception("Already kept");var water=AssetDatabase.LoadAssetAtPath<UnityEngine.Mesh>("Assets/World/WorldExtensions/Generated/NorthReference20261001/NorthInlandIcyWater20261006.asset").vertices;var vertices=new List<Vector3>();var indices=new List<int>();var uv=new List<Vector2>();
  Action<Vector3[]> polygon=p=>{int k=vertices.Count;foreach(var v in p){vertices.Add(v);uv.Add(new Vector2(v.x*.18f,v.z*.18f));}for(int j=1;j<p.Length-1;j++){indices.Add(k);indices.Add(k+j+1);indices.Add(k+j);}};
  for(int i=1;i<=72;i++)
  {int j=i==72?1:i+1;var a=water[i];var b=water[j];if(Channel((a+b)*.5f,water)<20)continue;float width=3+6*Mathf.PerlinNoise(i*.27f,19);var innerA=Vector3.MoveTowards(a,water[0],width);var innerB=Vector3.MoveTowards(b,water[0],width*(.65f+.4f*Mathf.Sin(i)));var p=new[]{a,innerA,innerB,b};for(int k=0;k<4;k++)p[k].y=21.09f+.015f*Mathf.Sin(i+k);polygon(p);}
  foreach(var plate in new[]{new Vector4(-66,1000,8,3),new Vector4(-40,990,10,4),new Vector4(9,997,9,3),new Vector4(-12,1038,7,4),new Vector4(42,1024,5,3)})
  {var p=new Vector3[9];for(int j=0;j<p.Length;j++){float angle=j*2*Mathf.PI/p.Length,r=.8f+.2f*Mathf.Sin(j*3.1f+plate.x);p[j]=new Vector3(plate.x+Mathf.Cos(angle)*plate.z*r,21.10f+.02f*Mathf.Sin(j),plate.y+Mathf.Sin(angle)*plate.w*r);}if(p.All(v=>InLake(v,water)&&Channel(v,water)>18))polygon(p);}
  var mesh=new UnityEngine.Mesh{name="NorthLakeShoreIce20261007"};mesh.SetVertices(vertices);mesh.SetUVs(0,uv);mesh.SetTriangles(indices,0);mesh.normals=Enumerable.Repeat(Vector3.up,vertices.Count).ToArray();mesh.RecalculateBounds();var material=new Material(Shader.Find("MMUnity/Iceberg")){name="ColdBrokenLakeIce20261007"};material.SetColor("_Color",new Color(.72f,.85f,.91f,1));material.SetTexture("_MainTex",AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/World/WorldExtensions/Generated/LinkedSnow02/Snow02_SeamlessAlbedoSmoothness.png"));material.SetTexture("_BumpMap",AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/EnvironmentAssets/UnitySamples/rock_boulder_cracked_n.png"));material.SetFloat("_BumpScale",.14f);material.SetFloat("_Glossiness",.55f);var root=new GameObject(name);root.hideFlags=HideFlags.HideAndDontSave;root.AddComponent<MeshFilter>().sharedMesh=mesh;root.AddComponent<MeshRenderer>().sharedMaterial=material;bool saved=false;
  try{string dir="Preview/NorthAuthored20261007/LakeIce/";Directory.CreateDirectory(dir);MMNorthAuthoredTools20261007.Capture(dir,"lake",new Vector3(-35,53,920),new Vector3(15,24,1070),false);MMNorthAuthoredTools20261007.Capture(dir,"top",new Vector3(0,850,1024),new Vector3(0,0,1024),true);
   if(keep){var scene=SceneManager.GetActiveScene();string backup="Backups/NorthAuthored20261007/LakeIceBefore";Directory.CreateDirectory(backup);if(!File.Exists(backup+"/Enroth.unity"))File.Copy(scene.path,backup+"/Enroth.unity");Directory.CreateDirectory(Dir);AssetDatabase.CreateAsset(mesh,Dir+"/LakeIce.asset");AssetDatabase.CreateAsset(material,Dir+"/LakeIce.mat");root.hideFlags=HideFlags.None;AssetDatabase.SaveAssetIfDirty(mesh);AssetDatabase.SaveAssetIfDirty(material);EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new IOException("Save failed");saved=true;File.WriteAllText("Validation/SequentialRepair/lake_ice_finished.txt","Thin irregular lake shore ice and five sheltered drifting plates; all three channel mouths open.");}
  }finally{if(!saved){UnityEngine.Object.DestroyImmediate(root);UnityEngine.Object.DestroyImmediate(mesh);UnityEngine.Object.DestroyImmediate(material);}}
 }
}


