using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using UnityEditor.SceneManagement;
using static MMNorthAuthoredTools20261007;
public static class MMNorthCanonicalTransition20261007
{
 public static void Run(int square,bool keep=false)
 {
  if(square<0||square>3)throw new ArgumentOutOfRangeException("square");var scene=SceneManager.GetActiveScene();if(scene.isDirty||scene.path!="Assets/Scenes/World/Enroth.unity")throw new Exception("Need saved Enroth");string rootName="North Canonical Woodland Transition "+square+" 20261007";if(GameObject.Find(rootName))throw new Exception("Already saved");
  float origin=-1280+512*square;var north=Terrain.activeTerrains.First(t=>t.transform.position.x==origin&&t.transform.position.z==768);var south=Terrain.activeTerrains.First(t=>t.transform.position.x==origin&&t.transform.position.z==256);var original=north.terrainData;var clone=UnityEngine.Object.Instantiate(original);clone.hideFlags=HideFlags.HideAndDontSave;var layers=original.terrainLayers.ToList();var edge=south.terrainData.GetAlphamaps(0,south.terrainData.alphamapHeight-1,south.terrainData.alphamapWidth,1);var sourceLayers=south.terrainData.terrainLayers;var map=new int[sourceLayers.Length];
  for(int l=0;l<sourceLayers.Length;l++){bool used=false;for(int x=0;x<edge.GetLength(1);x++)if(edge[0,x,l]>.001f){used=true;break;}map[l]=layers.IndexOf(sourceLayers[l]);if(map[l]<0&&used){map[l]=layers.Count;layers.Add(sourceLayers[l]);}}
  var old=original.GetAlphamaps(0,0,original.alphamapWidth,original.alphamapHeight);var alpha=new float[old.GetLength(0),old.GetLength(1),layers.Count];for(int z=0;z<old.GetLength(0);z++)for(int x=0;x<old.GetLength(1);x++)for(int l=0;l<old.GetLength(2);l++)alpha[z,x,l]=old[z,x,l];int band=Mathf.CeilToInt(92f/512*old.GetLength(0));
  for(int x=0;x<old.GetLength(1);x++){float wx=origin+512f*x/(old.GetLength(1)-1),sx=x*(edge.GetLength(1)-1f)/(old.GetLength(1)-1);int ix=Mathf.Min((int)sx,edge.GetLength(1)-2);float u=sx-ix;float feather=48+40*Mathf.PerlinNoise(wx*.014f+21,8);for(int z=0;z<band;z++){float fade=S(0,feather,512f*z/(old.GetLength(0)-1));for(int l=0;l<layers.Count;l++)alpha[z,x,l]*=fade;float sum=0;for(int l=0;l<map.Length;l++)if(map[l]>=0){float w=(1-fade)*Mathf.Lerp(edge[0,ix,l],edge[0,ix+1,l],u);alpha[z,x,map[l]]+=w;sum+=w;}if(sum<1-fade-.0001f){float total=0;for(int l=0;l<layers.Count;l++)total+=alpha[z,x,l];if(total>0)for(int l=0;l<layers.Count;l++)alpha[z,x,l]/=total;}}}
  GameObject root=null;bool saved=false;
  try
  {
   clone.terrainLayers=layers.ToArray();clone.SetAlphamaps(0,0,alpha);clone.SetBaseMapDirty();north.terrainData=clone;north.GetComponent<TerrainCollider>().terrainData=clone;north.Flush();
   root=new GameObject(rootName);root.hideFlags=HideFlags.HideAndDontSave;var mature=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/TempDragonTemplate/TracePine.prefab");var young=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/TempDragonTemplate/TraceYoungPine.prefab");if(!mature||!young)throw new Exception("Production conifers missing");var random=new System.Random(84001+square);var occupied=UnityEngine.Object.FindObjectsByType<Transform>().Where(t=>t.name.StartsWith("AuthoredPine_")||t.name.StartsWith("SourceTree_")||t.name.StartsWith("Eco_")).Select(t=>new Vector2(t.position.x,t.position.z)).ToList();
   for(float z=682;z<818;z+=8.5f)for(float x=origin+12;x<origin+500;x+=8.5f)
   {
    float px=x+(float)random.NextDouble()*6-3,pz=z+(float)random.NextDouble()*6-3;var t=pz<768?south:north;float y=Ground(t,px,pz),u=(px-origin)/512,v=(pz-t.transform.position.z)/512;if(y<.85f||y>62||t.terrainData.GetSteepness(u,v)>26)continue;
    if(Ground(t,px-3,pz)<.5f||Ground(t,px+3,pz)<.5f||Ground(t,px,pz-3)<.5f||Ground(t,px,pz+3)<.5f)continue;float density=S(682,748,pz)*(.2f+.65f*Mathf.PerlinNoise(px*.019f+31,pz*.019f+11))*(1-S(40,62,y));if(random.NextDouble()>density)continue;if(occupied.Any(p=>(p-new Vector2(px,pz)).sqrMagnitude<36))continue;
    var weights=t.terrainData.GetAlphamaps(Mathf.Clamp((int)(u*t.terrainData.alphamapWidth),0,t.terrainData.alphamapWidth-1),Mathf.Clamp((int)(v*t.terrainData.alphamapHeight),0,t.terrainData.alphamapHeight-1),1,1);float road=0;for(int l=0;l<t.terrainData.terrainLayers.Length;l++)if(t.terrainData.terrainLayers[l].name.Contains("Road"))road+=weights[0,0,l];if(road>.08f)continue;
    if(Physics.OverlapSphere(new Vector3(px,y+2,pz),3.5f).Any(c=>!(c is TerrainCollider)&&!c.isTrigger))continue;
    var source=root.transform.childCount%5==0?young:mature;var tree=UnityEngine.Object.Instantiate(source,root.transform);tree.name="TransitionPine_"+root.transform.childCount;tree.hideFlags=HideFlags.HideAndDontSave;tree.transform.position=new Vector3(px,y,pz);tree.transform.rotation=Quaternion.Euler(0,(float)random.NextDouble()*360,0)*source.transform.rotation;tree.transform.localScale=source.transform.localScale*(1.15f+.5f*(float)random.NextDouble());var managed=new HashSet<Renderer>();foreach(var group in tree.GetComponentsInChildren<LODGroup>()){var selected=group.GetLODs().Take(2).ToArray();if(selected.Length>0){selected[selected.Length-1].screenRelativeTransitionHeight=.0015f;group.SetLODs(selected);foreach(var l in selected)foreach(var r in l.renderers)if(r)managed.Add(r);}}foreach(var r in tree.GetComponentsInChildren<Renderer>())if(!managed.Contains(r))r.gameObject.SetActive(false);var rs=tree.GetComponentsInChildren<Renderer>();if(rs.Length>0){var b=rs[0].bounds;foreach(var r in rs.Skip(1))b.Encapsulate(r.bounds);tree.transform.position+=Vector3.up*(y-b.min.y-.12f);}occupied.Add(new Vector2(px,pz));
   }
   string dir="Preview/NorthCanonicalTransition20261007/Sq"+square+"/";Directory.CreateDirectory(dir);File.WriteAllText(dir+"stats.txt","trees="+root.transform.childCount+" addedLayers="+(layers.Count-original.terrainLayers.Length));Capture(dir,"top",new Vector3(origin+256,850,820),new Vector3(origin+256,0,820),true);Capture(dir,"transition",new Vector3(origin+256,155,530),new Vector3(origin+256,35,950),false);Capture(dir,"cross",new Vector3(origin-70,100,700),new Vector3(origin+280,25,805),false);
   if(keep){string backup="Backups/NorthCanonicalTransition20261007/Sq"+square;Directory.CreateDirectory(backup);foreach(var path in new[]{AssetDatabase.GetAssetPath(original),scene.path}){var dest=Path.Combine(backup,Path.GetFileName(path));if(!File.Exists(dest))File.Copy(path,dest);}original.terrainLayers=layers.ToArray();original.SetAlphamaps(0,0,alpha);original.SetBaseMapDirty();EditorUtility.SetDirty(original);AssetDatabase.SaveAssetIfDirty(original);north.terrainData=original;north.GetComponent<TerrainCollider>().terrainData=original;foreach(var tr in root.GetComponentsInChildren<Transform>(true))tr.gameObject.hideFlags=HideFlags.None;EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new IOException("Save failed");saved=true;File.WriteAllText("Validation/SequentialRepair/canonical_transition"+square+"_kept.txt","Extension-only material feather 48–88m; source edge layers added only where actually used. Outside strip weights preserved; heights unchanged. Scene-only woodland bridge count="+root.transform.childCount+". Canonical TerrainData read-only.");}
  }
  finally{north.terrainData=original;north.GetComponent<TerrainCollider>().terrainData=original;north.Flush();UnityEngine.Object.DestroyImmediate(clone);if(!saved&&root)UnityEngine.Object.DestroyImmediate(root);}
 }
}
