using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;
// Only the demonstrated material discontinuity at the extension's south edge.
// No whole-tile repaint, height write, new layer, or legacy TerrainData write.
public static class MMNorthLegacyMaterialEdge20261007
{
 public static void Run(int square,bool keep=false)
 {
  var scene=SceneManager.GetActiveScene();if(scene.isDirty||scene.path!="Assets/Scenes/World/Enroth.unity")throw new Exception("Need clean saved Enroth");string report="Validation/SequentialRepair/material_edge"+square+"_kept.txt";if(File.Exists(report))throw new Exception("Already kept");float origin=-1280+512*square;var terrain=Terrain.activeTerrains.First(t=>t.transform.position.x==origin&&t.transform.position.z==768);var south=Terrain.activeTerrains.First(t=>t.transform.position.x==origin&&t.transform.position.z==256);var original=terrain.terrainData;var source=south.terrainData;int width=original.alphamapWidth,band=Mathf.CeilToInt(56f/512*original.alphamapHeight);var patch=original.GetAlphamaps(0,0,width,band);var sourceEdge=source.GetAlphamaps(0,source.alphamapHeight-1,source.alphamapWidth,1);var layers=original.terrainLayers;var map=source.terrainLayers.Select(l=>Array.IndexOf(layers,l)).ToArray();if(map.Any(i=>i<0))throw new Exception("Missing shared layer: inspect instead of adding whole-tile layers");
  for(int x=0;x<width;x++){float wx=origin+x*512f/(width-1);float f=x*(source.alphamapWidth-1f)/(width-1);int sx=Mathf.Min((int)f,source.alphamapWidth-2);float u=f-sx;float feather=30+24*Mathf.PerlinNoise(wx*.017f+41,9);for(int z=0;z<band;z++){float distance=z*512f/original.alphamapHeight;float t=MMNorthAuthoredTools20261007.S(0,feather,distance);for(int l=0;l<layers.Length;l++)patch[z,x,l]*=t;for(int l=0;l<map.Length;l++)patch[z,x,map[l]]+=(1-t)*Mathf.Lerp(sourceEdge[0,sx,l],sourceEdge[0,sx+1,l],u);}}
  var clone=UnityEngine.Object.Instantiate(original);clone.hideFlags=HideFlags.HideAndDontSave;var collider=terrain.GetComponent<TerrainCollider>();try{clone.SetAlphamaps(0,0,patch);terrain.terrainData=clone;if(collider)collider.terrainData=clone;terrain.Flush();string dir="Preview/NorthAuthored20261007/MaterialEdge"+square+"/";Directory.CreateDirectory(dir);float center=origin+256;MMNorthAuthoredTools20261007.Capture(dir,"top",new Vector3(center,850,1024),new Vector3(center,0,1024),true);MMNorthAuthoredTools20261007.Capture(dir,"transition",new Vector3(center,155,530),new Vector3(center,35,950),false);
   if(keep){string backup="Backups/NorthAuthored20261007/MaterialEdge"+square+"Before";Directory.CreateDirectory(backup);string path=AssetDatabase.GetAssetPath(original),dst=Path.Combine(backup,Path.GetFileName(path));if(!File.Exists(dst))File.Copy(path,dst);original.SetAlphamaps(0,0,patch);EditorUtility.SetDirty(original);AssetDatabase.SaveAssetIfDirty(original);File.WriteAllText(report,"Specific legacy colour seam feathered in extension-only 30-54m strip. Existing shared layers only; heightfield, legacy assets and all weights outside strip unchanged.");}
  }finally{terrain.terrainData=original;if(collider)collider.terrainData=original;terrain.Flush();UnityEngine.Object.DestroyImmediate(clone);}
 }
}
