using System;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEditor;
public static class MMNorthAuthoredTools20261007 {
 public static float S(float a,float b,float v){float t=Mathf.Clamp01((v-a)/(b-a));return t*t*(3-2*t);}
 public static float Ground(Terrain t,float x,float z){return t.SampleHeight(new Vector3(x,0,z))+t.transform.position.y;}
 public static float Ridge(float x,float z,Vector4[] p){float best=0;for(int i=0;i<p.Length-1;i++){Vector2 a=new Vector2(p[i].x,p[i].y),b=new Vector2(p[i+1].x,p[i+1].y),ab=b-a;float q=Mathf.Clamp01(Vector2.Dot(new Vector2(x,z)-a,ab)/ab.sqrMagnitude);Vector2 c=a+q*ab;float signed=(ab.x*(z-c.y)-ab.y*(x-c.x))/ab.magnitude;float d=Mathf.Abs(signed+2.4f*Mathf.Sin((c.x+c.y)*.11f));float width=Mathf.Lerp(p[i].w,p[i+1].w,q)*1.35f*(signed<0?.9f:1.12f);float longitudinal=Vector2.Distance(new Vector2(x,z),c);if(q==0||q==1)d=longitudinal;float k=Mathf.Clamp01(1-d/width);float face=.75f*k+.25f*Mathf.Pow(k,2.2f);float crest=Mathf.Lerp(p[i].z,p[i+1].z,q);float rib=.72f;best=Mathf.Max(best,crest*face*rib);}return best;}
 public static float H(float[,] h,float x,float z){int ix=(int)x,iz=(int)z;float u=x-ix,v=z-iz;return Mathf.Lerp(Mathf.Lerp(h[iz,ix],h[iz,ix+1],u),Mathf.Lerp(h[iz+1,ix],h[iz+1,ix+1],u),v)*320-24;}
 public static void Erode(float[,] h){var random=new System.Random(42007);for(int n=0;n<68000;n++){float x=32+(float)random.NextDouble()*448,z=62+(float)random.NextDouble()*418;float dx=0,dz=0,speed=1,water=1,sediment=0;for(int age=0;age<60;age++){if(x<33||x>478||z<63||z>478)break;float height=H(h,x,z);if(height<18)break;float gx=(H(h,x+.5f,z)-H(h,x-.5f,z)),gz=(H(h,x,z+.5f)-H(h,x,z-.5f));dx=dx*.12f-gx*.88f;dz=dz*.12f-gz*.88f;float len=Mathf.Sqrt(dx*dx+dz*dz);if(len<.0001f)break;dx/=len;dz/=len;float nx=x+dx,nz=z+dz;if(nx<32||nx>479||nz<62||nz>479)break;float delta=H(h,nx,nz)-height;float capacity=Mathf.Max(.04f,-delta*speed*water*4);int ix=(int)x,iz=(int)z;if(sediment>capacity||delta>0){float deposit=delta>0?Mathf.Min(delta,sediment):(sediment-capacity)*.18f;sediment-=deposit;float u=x-ix,v=z-iz;h[iz,ix]+=deposit*(1-u)*(1-v)/320;h[iz,ix+1]+=deposit*u*(1-v)/320;h[iz+1,ix]+=deposit*(1-u)*v/320;h[iz+1,ix+1]+=deposit*u*v/320;}else{float amount=Mathf.Min((capacity-sediment)*.24f,Mathf.Max(0,-delta));float total=0;for(int bz=-2;bz<=2;bz++)for(int bx=-2;bx<=2;bx++){float w=Mathf.Max(0,1-Mathf.Sqrt(bx*bx+bz*bz)/2.5f);total+=w;}for(int bz=-2;bz<=2;bz++)for(int bx=-2;bx<=2;bx++){float w=Mathf.Max(0,1-Mathf.Sqrt(bx*bx+bz*bz)/2.5f)/total;float available=Mathf.Max(0,h[iz+bz,ix+bx]*320-24-16);float take=Mathf.Min(available,amount*w);h[iz+bz,ix+bx]-=take/320;sediment+=take;}}speed=Mathf.Sqrt(Mathf.Max(0,speed*speed-delta*3));water*=.975f;x=nx;z=nz;}}}
 public static GameObject SeaPreview(Terrain t){var original=UnityEngine.Object.FindObjectsByType<MeshRenderer>().First(r=>r.name=="Linked connected sea and existing lowland waters 20260929");var g=new GameObject("__TemporarySeaOccupancy");g.hideFlags=HideFlags.HideAndDontSave;g.AddComponent<MeshRenderer>().sharedMaterial=original.sharedMaterial;var m=new UnityEngine.Mesh();m.indexFormat=UnityEngine.Rendering.IndexFormat.UInt32;var v=new System.Collections.Generic.List<Vector3>();var tr=new System.Collections.Generic.List<int>();for(int z=(int)t.transform.position.z;z<t.transform.position.z+512;z+=2)for(int x=(int)t.transform.position.x;x<t.transform.position.x+512;x+=2){bool wet=true;for(int dz=0;dz<=2;dz++)for(int dx=0;dx<=2;dx++)if(Ground(t,x+dx,z+dz)>.10f)wet=false;if(!wet)continue;int k=v.Count;v.Add(new Vector3(x,.122f,z));v.Add(new Vector3(x,.122f,z+2));v.Add(new Vector3(x+2,.122f,z+2));v.Add(new Vector3(x+2,.122f,z));tr.Add(k);tr.Add(k+1);tr.Add(k+2);tr.Add(k);tr.Add(k+2);tr.Add(k+3);}m.SetVertices(v);m.SetTriangles(tr,0);m.RecalculateNormals();m.RecalculateBounds();g.AddComponent<MeshFilter>().sharedMesh=m;return g;}
 public static void Capture(string dir,string n,Vector3 p,Vector3 target,bool top){var g=new GameObject("__NorthQA");g.hideFlags=HideFlags.HideAndDontSave;var c=g.AddComponent<Camera>();c.enabled=false;c.transform.position=p;c.transform.rotation=top?Quaternion.Euler(90,0,0):Quaternion.LookRotation(target-p);c.orthographic=top;c.orthographicSize=310;c.fieldOfView=60;c.nearClipPlane=.15f;c.farClipPlane=4000;c.depthTextureMode=DepthTextureMode.Depth;c.clearFlags=CameraClearFlags.Skybox;var rt=new RenderTexture(1400,1000,24);var old=RenderTexture.active;Texture2D tx=null;try{c.targetTexture=rt;c.Render();c.Render();RenderTexture.active=rt;tx=new Texture2D(1400,1000,TextureFormat.RGB24,false);tx.ReadPixels(new Rect(0,0,1400,1000),0,0);tx.Apply();File.WriteAllBytes(dir+n+".png",tx.EncodeToPNG());}finally{RenderTexture.active=old;c.targetTexture=null;if(tx)UnityEngine.Object.DestroyImmediate(tx);UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(g);}}

}
