using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;

// A single world-space field, including shared masks, avoids per-tile rims.
public static class MMTerrainRealism20261007
{
 static float S(float a,float b,float v)=>Mathf.SmoothStep(0,1,Mathf.InverseLerp(a,b,v));
 const string Root="Validation/TerrainRealism20261007/";
 static bool Tree(Transform t) {string n=t.name.ToLowerInvariant();return n.StartsWith("authoredpine_")||n.StartsWith("dragonauthoredpine_")||n.StartsWith("transitionpine_")||n.StartsWith("referencetallpine_")||n.StartsWith("pine_")||n.StartsWith("pine00")||n.StartsWith("youngpine_")||n.StartsWith("pinedead_")||n.StartsWith("sourcetree_")||n.StartsWith("conifer_")||n.StartsWith("eco_tree")||n.StartsWith("eco_pine");}
 static bool Dressing(Transform t)=>Tree(t)||t.name.StartsWith("Rock_")||t.name.StartsWith("AuthoredBoulder_")||t.name.StartsWith("DragonAuthoredBoulder_")||t.name.StartsWith("Bush_")||t.name.StartsWith("Eco_");
 static float Sample(float[,] a,float x,float z) {int nx=a.GetLength(1),nz=a.GetLength(0);x=Mathf.Clamp(x,0,nx-1);z=Mathf.Clamp(z,0,nz-1);int ix=Mathf.Min(nx-2,(int)x),iz=Mathf.Min(nz-2,(int)z);return Mathf.Lerp(Mathf.Lerp(a[iz,ix],a[iz,ix+1],x-ix),Mathf.Lerp(a[iz+1,ix],a[iz+1,ix+1],x-ix),z-iz);}
 static float[,] Blur(float[,] a,int radius) {
  int nz=a.GetLength(0),nx=a.GetLength(1);var b=new float[nz,nx];var c=new float[nz,nx];int w=2*radius+1;
  for(int z=0;z<nz;z++){double sum=0;for(int k=-radius;k<=radius;k++)sum+=a[z,Mathf.Clamp(k,0,nx-1)];for(int x=0;x<nx;x++){b[z,x]=(float)(sum/w);sum+=a[z,Mathf.Min(nx-1,x+radius+1)]-a[z,Mathf.Max(0,x-radius)];}}
  for(int x=0;x<nx;x++){double sum=0;for(int k=-radius;k<=radius;k++)sum+=b[Mathf.Clamp(k,0,nz-1),x];for(int z=0;z<nz;z++){c[z,x]=(float)(sum/w);sum+=b[Mathf.Min(nz-1,z+radius+1),x]-b[Mathf.Max(0,z-radius),x];}}return c;
 }
 static int[] SnowSlots(TerrainData d)=>Enumerable.Range(0,d.terrainLayers.Length).Where(i=>d.terrainLayers[i]&&((d.terrainLayers[i].name+" "+(d.terrainLayers[i].diffuseTexture?d.terrainLayers[i].diffuseTexture.name:"")).ToLower().Contains("snow"))).ToArray();
 public static void Landscape(bool realistic,bool save=false) {
  var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();if(Application.isPlaying||scene.isDirty)throw new Exception("Clean Edit Mode required");
  string mode=realistic?"Realistic":"Canonical",dir=Root+mode+"/";if(File.Exists(dir+"saved.txt"))throw new Exception("Already applied; use baseline, never cumulative");
  var ts=MMTerrainBranchContrast20261007.Tiles();if(ts.Any(t=>EditorUtility.IsDirty(t.terrainData)))throw new Exception("Save or reload dirty TerrainData before authoring");if(ts.Any(t=>t.terrainData.heightmapResolution!=513||t.terrainData.size!=new Vector3(512,320,512)||t.transform.position.y!= -24))throw new Exception("Unexpected world grid layout");int ox=(int)ts.Min(t=>t.transform.position.x),oz=(int)ts.Min(t=>t.transform.position.z),nx=(int)ts.Max(t=>t.transform.position.x)-ox+513,nz=(int)ts.Max(t=>t.transform.position.z)-oz+513;
  var grid=new float[nz,nx];var mask=new float[nz,nx];for(int z=0;z<nz;z++)for(int x=0;x<nx;x++)mask[z,x]=1;
  var old=new Dictionary<Terrain,float[,]>();var next=new Dictionary<Terrain,float[,]>();
  foreach(var t in ts){var h=t.terrainData.GetHeights(0,0,513,513);old[t]=h;var road=MMTerrainBranchContrast20261007.Roads(t.terrainData);var water=MMTerrainBranchContrast20261007.WaterDistance(t);var zones=MMTerrainBranchContrast20261007.Protected(t);int tx=(int)t.transform.position.x-ox,tz=(int)t.transform.position.z-oz;
   for(int z=0;z<=512;z++)for(int x=0;x<=512;x++){float y=h[z,x]*320-24,wx=x+tx+ox,wz=z+tz+oz;grid[z+tz,x+tx]=y;float w=S(realistic?2:12,realistic?16:28,y)*(1-S(.005f,.035f,road[z,x]))*S(9,65,water[z,x]);foreach(var b in zones){float dx=Mathf.Max(b.min.x-wx,Mathf.Max(0,wx-b.max.x)),dz=Mathf.Max(b.min.z-wz,Mathf.Max(0,wz-b.max.z));w*=S(0,42,Mathf.Sqrt(dx*dx+dz*dz));}if(!realistic){bool extension=(t.transform.position.z==768&&t.transform.position.x>=-1280&&t.transform.position.x<=256)||(t.transform.position.x==-1792&&t.transform.position.z>=256)||(t.transform.position.z==-1280&&t.transform.position.x>=256);if(!extension)w=0;else {if(t.transform.position.z==768&&t.transform.position.x>=-1280)w*=S(0,110,z);if(t.transform.position.x==-1792&&t.transform.position.z==256)w*=1-S(402,512,x);if(t.transform.position.z==-1280)w*=1-S(402,512,z);}}mask[z+tz,x+tx]=Mathf.Min(mask[z+tz,x+tx],w);}
  }
  var fine=Blur(Blur(grid,10),10);var broad=Blur(Blur(grid,32),32);var massif=realistic?Blur(Blur(grid,64),64):Blur(Blur(grid,48),48);var target=new float[nz,nx];
  for(int z=0;z<nz;z++)for(int x=0;x<nx;x++){
   float seam=1000;for(int b=512;b<nx-1;b+=512)seam=Mathf.Min(seam,Mathf.Abs(x-b));for(int b=512;b<nz-1;b+=512)seam=Mathf.Min(seam,Mathf.Abs(z-b));
   // Wide shared foothills replace the former rigid rims. No periodic ridge noise.
   float boundary=1-S(45,200,seam),y;
   if(realistic){float form=Mathf.Lerp(fine[z,x],broad[z,x],.12f+.48f*boundary);y=form;}
   else {float form=Mathf.Lerp(broad[z,x],massif[z,x],.8f);y=10+Mathf.Max(0,form-10)*.61f;}
   float edge=S(0,38,Mathf.Min(Mathf.Min(x,nx-1-x),Mathf.Min(z,nz-1-z)));target[z,x]=Mathf.Lerp(grid[z,x],y,mask[z,x]*edge);
  }
  // Conservative talus relaxation softens isolated spikes while keeping real cliffs.
  if(realistic)for(int iteration=0;iteration<10;iteration++){var delta=new float[nz,nx];for(int z=1;z<nz-1;z++)for(int x=1;x<nx-1;x++){if(mask[z,x]<.01f)continue;float y=target[z,x],drop=0;int bx=x,bz=z;for(int dz=-1;dz<=1;dz++)for(int dx=-1;dx<=1;dx++){float d=y-target[z+dz,x+dx]-1.15f*Mathf.Sqrt(dx*dx+dz*dz);if(d>drop){drop=d;bx=x+dx;bz=z+dz;}}float amount=Mathf.Min(.45f,drop*.15f)*Mathf.Min(mask[z,x],mask[bz,bx]);delta[z,x]-=amount;delta[bz,bx]+=amount;}for(int z=1;z<nz-1;z++)for(int x=1;x<nx-1;x++)target[z,x]+=delta[z,x];}
  if(realistic)RoundJoins(target,mask);float max=0;foreach(var t in ts){int tx=(int)t.transform.position.x-ox,tz=(int)t.transform.position.z-oz;var h=(float[,])old[t].Clone();for(int z=0;z<=512;z++)for(int x=0;x<=512;x++){h[z,x]=(target[z+tz,x+tx]+24)/320;max=Mathf.Max(max,Mathf.Abs(h[z,x]-old[t][z,x])*320);}next[t]=h;}
  Directory.CreateDirectory(dir);File.WriteAllText(dir+"seams.txt",Seams(ts,old,next));
  var moved=new Dictionary<Transform,Vector3>();var meshes=new Dictionary<Mesh,Vector3[]>();bool kept=false;
  try {
   foreach(var t in ts){if(save){string backup="Backups/TerrainRealism20261007/"+mode+"/"+MMTerrainBranchContrast20261007.Key(t);Directory.CreateDirectory(backup);string p=AssetDatabase.GetAssetPath(t.terrainData);if(!File.Exists(backup+"/Terrain.asset"))File.Copy(p,backup+"/Terrain.asset");}t.terrainData.SetHeights(0,0,next[t]);t.Flush();}
   foreach(var tr in UnityEngine.Object.FindObjectsByType<Transform>()){if(!Dressing(tr)||tr.GetComponentsInParent<Transform>().Skip(1).Any(Dressing))continue;var p=tr.position;var t=ts.FirstOrDefault(a=>p.x>=a.transform.position.x&&p.x<a.transform.position.x+512&&p.z>=a.transform.position.z&&p.z<a.transform.position.z+512);if(!t)continue;float d=t.terrainData.GetInterpolatedHeight((p.x-t.transform.position.x)/512,(p.z-t.transform.position.z)/512)-Sample(old[t],p.x-t.transform.position.x,p.z-t.transform.position.z)*320;if(Mathf.Abs(d)>.001f){moved[tr]=p;tr.position+=Vector3.up*d;}}
   foreach(var f in UnityEngine.Object.FindObjectsByType<MeshFilter>()){if(!(f.name.StartsWith("North Alpine Rock Surface")||f.name.StartsWith("DragonRockSurface")||f.name.StartsWith("Northern World Rock "))||!f.sharedMesh)continue;var m=f.sharedMesh;if(meshes.ContainsKey(m))continue;var v=m.vertices;meshes[m]=(Vector3[])v.Clone();for(int i=0;i<v.Length;i++){var p=f.transform.TransformPoint(v[i]);float gx=p.x-ox,gz=p.z-oz;if(gx<0||gx>nx-1||gz<0||gz>nz-1)continue;p.y+=Sample(target,gx,gz)-Sample(grid,gx,gz);v[i]=f.transform.InverseTransformPoint(p);}m.vertices=v;m.RecalculateNormals();m.RecalculateBounds();m.UploadMeshData(false);}
   Capture(mode);if(!realistic)foreach(var t in ts.Where(t=>(t.transform.position.z==768&&t.transform.position.x>=-1280&&t.transform.position.x<=256)||(t.transform.position.x==-1792&&t.transform.position.z>=256)||(t.transform.position.z==-1280&&t.transform.position.x>=256))){string q="Preview/TerrainRealism20261007/Canonical/"+MMTerrainBranchContrast20261007.Key(t)+"/";Directory.CreateDirectory(q);MMTerrainBranchContrast20261007.Capture(t,q);}
   if(save){foreach(var t in ts){EditorUtility.SetDirty(t.terrainData);AssetDatabase.SaveAssetIfDirty(t.terrainData);}foreach(var m in meshes.Keys){EditorUtility.SetDirty(m);AssetDatabase.SaveAssetIfDirty(m);}EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new Exception("Scene save failed");File.WriteAllText(dir+"saved.txt","maximumDelta="+max+" moved="+moved.Count+" overlays="+meshes.Count);kept=true;}
   Debug.Log("LANDSCAPE "+mode+" saved="+save+" maxDelta="+max+" "+File.ReadAllText(dir+"seams.txt"));
  } finally {if(!kept){foreach(var t in ts){t.terrainData.SetHeights(0,0,old[t]);t.Flush();EditorUtility.ClearDirty(t.terrainData);}foreach(var p in moved)p.Key.position=p.Value;foreach(var p in meshes){p.Key.vertices=p.Value;p.Key.RecalculateNormals();p.Key.RecalculateBounds();p.Key.UploadMeshData(false);}}}
 }
 static void RoundJoins(float[,] h,float[,] mask){int nz=h.GetLength(0),nx=h.GetLength(1),radius=48;for(int axis=0;axis<2;axis++){var src=(float[,])h.Clone();int length=axis==0?nx:nz,lines=axis==0?nz:nx;for(int b=512;b<length-1;b+=512)for(int k=0;k<lines;k++){Func<int,float> v=i=>axis==0?src[k,i]:src[i,k];Func<int,float> w=i=>axis==0?mask[k,i]:mask[i,k];float low=v(b-radius),high=v(b+radius),dl=(low-v(b-radius-8))/8,dh=(v(b+radius+8)-high)/8;float limit=Mathf.Abs(high-low)/(2*radius)+.3f;dl=Mathf.Clamp(dl,-limit,limit);dh=Mathf.Clamp(dh,-limit,limit);for(int i=-radius;i<=radius;i++){float u=(i+radius)/(2f*radius),u2=u*u,u3=u2*u;float y=(2*u3-3*u2+1)*low+(u3-2*u2+u)*2*radius*dl+(-2*u3+3*u2)*high+(u3-u2)*2*radius*dh;float weight=Mathf.Min(w(b+i),w(b))*S(0,12,radius-Mathf.Abs(i));if(axis==0)h[k,b+i]=Mathf.Lerp(src[k,b+i],y,weight);else h[b+i,k]=Mathf.Lerp(src[b+i,k],y,weight);}}}}
 static string Seams(Terrain[] ts,Dictionary<Terrain,float[,]> before,Dictionary<Terrain,float[,]> after){double bsum=0,asum=0;float gap=0,worstBefore=0,worstAfter=0;int joins=0,samples=0;foreach(var a in ts)foreach(var b in ts){var d=b.transform.position-a.transform.position;bool east=d==new Vector3(512,0,0),north=d==new Vector3(0,0,512);if(!east&&!north)continue;joins++;var ah=before[a];var bh=before[b];var an=after[a];var bn=after[b];for(int k=1;k<512;k++){float bj=Mathf.Abs(east?(ah[k,512]-ah[k,504])-(bh[k,8]-bh[k,0]):(ah[512,k]-ah[504,k])-(bh[8,k]-bh[0,k]))*40,aj=Mathf.Abs(east?(an[k,512]-an[k,504])-(bn[k,8]-bn[k,0]):(an[512,k]-an[504,k])-(bn[8,k]-bn[0,k]))*40;bsum+=bj;asum+=aj;worstBefore=Mathf.Max(worstBefore,bj);worstAfter=Mathf.Max(worstAfter,aj);gap=Mathf.Max(gap,Mathf.Abs(east?an[k,512]-bn[k,0]:an[512,k]-bn[0,k])*320);samples++;}}return "joins="+joins+" gap="+gap+" meanBefore="+bsum/samples+" meanAfter="+asum/samples+" worstBefore="+worstBefore+" worstAfter="+worstAfter;}
 public static void Capture(string mode){string dir="Preview/TerrainRealism20261007/"+mode+"/";Directory.CreateDirectory(dir);MMNorthAuthoredTools20261007.Capture(dir,"western_join",new Vector3(-1350,200,500),new Vector3(-850,55,850),false);MMNorthAuthoredTools20261007.Capture(dir,"south_join",new Vector3(-310,170,550),new Vector3(-150,40,860),false);MMNorthAuthoredTools20261007.Capture(dir,"north",new Vector3(-480,230,600),new Vector3(-250,70,1030),false);MMNorthAuthoredTools20261007.Capture(dir,"desert",new Vector3(-1000,190,-1200),new Vector3(-600,30,-700),false);}
 public static void BlendSnowTransitions(){
  if(Application.isPlaying)throw new Exception("Edit Mode required");var ts=MMTerrainBranchContrast20261007.Tiles();if(ts.Any(t=>EditorUtility.IsDirty(t.terrainData)))throw new Exception("Save or reload dirty TerrainData before authoring");if(ts.Any(t=>t.terrainData.heightmapResolution!=513||t.terrainData.size!=new Vector3(512,320,512)||t.transform.position.y!= -24))throw new Exception("Unexpected world grid layout");int ox=(int)ts.Min(t=>t.transform.position.x),oz=(int)ts.Min(t=>t.transform.position.z),nx=((int)ts.Max(t=>t.transform.position.x)-ox)/4+129,nz=((int)ts.Max(t=>t.transform.position.z)-oz)/4+129;var field=new float[nz,nx];var paints=ts.ToDictionary(t=>t,t=>t.terrainData.GetAlphamaps(0,0,t.terrainData.alphamapWidth,t.terrainData.alphamapHeight));
  foreach(var t in ts){var a=paints[t];var snow=SnowSlots(t.terrainData);int tx=((int)t.transform.position.x-ox)/4,tz=((int)t.transform.position.z-oz)/4;for(int z=0;z<=128;z++)for(int x=0;x<=128;x++){float v=0;foreach(int k in snow)v+=a[Mathf.Min(a.GetLength(0)-1,z*a.GetLength(0)/128),Mathf.Min(a.GetLength(1)-1,x*a.GetLength(1)/128),k];field[tz+z,tx+x]=v;}}
  var snowLookup=ts.ToDictionary(t=>t,t=>SnowSlots(t.terrainData));var soft=Blur(Blur(field,6),6);int changed=0;
  foreach(var t in ts){var d=t.terrainData;var a=paints[t];var snow=SnowSlots(d);if(snow.Length==0)continue;var road=Enumerable.Range(0,d.terrainLayers.Length).Where(i=>d.terrainLayers[i]&&((d.terrainLayers[i].name+" "+(d.terrainLayers[i].diffuseTexture?d.terrainLayers[i].diffuseTexture.name:"")).ToLower().Contains("road")||(d.terrainLayers[i].diffuseTexture&&d.terrainLayers[i].diffuseTexture.name.ToLower().Contains("stone_ground")))).ToArray();int h=a.GetLength(0),w=a.GetLength(1);for(int z=0;z<h;z++)for(int x=0;x<w;x++){float wx=t.transform.position.x+(x+.5f)*512/w,wz=t.transform.position.z+(z+.5f)*512/h,gx=(wx-ox)/4,gz=(wz-oz)/4,seam=1000;for(int b=128;b<nx-1;b+=128)seam=Mathf.Min(seam,Mathf.Abs(gx-b)*4);for(int b=128;b<nz-1;b+=128)seam=Mathf.Min(seam,Mathf.Abs(gz-b)*4);float blend=1-S(18,90,seam);if(blend==0)continue;float s=0,r=0;foreach(int k in snow)s+=a[z,x,k];foreach(int k in road)r+=a[z,x,k];float desired=Mathf.Clamp(Sample(soft,gx,gz),0,1-r);float ns=Mathf.Lerp(s,desired,blend*.88f);if(Mathf.Abs(ns-s)<.0001f)continue;int dominant=-1;float largest=0;for(int k=0;k<a.GetLength(2);k++)if(!snow.Contains(k)&&!road.Contains(k)&&a[z,x,k]>largest){largest=a[z,x,k];dominant=k;}if(dominant<0)dominant=Enumerable.Range(0,a.GetLength(2)).FirstOrDefault(k=>!snow.Contains(k)&&!road.Contains(k));float other=1-r-s;for(int k=0;k<a.GetLength(2);k++)if(!snow.Contains(k)&&!road.Contains(k))a[z,x,k]=other>.0001f?a[z,x,k]*(1-r-ns)/other:(k==dominant?1-r-ns:0);if(s>.0001f)foreach(int k in snow)a[z,x,k]*=ns/s;else a[z,x,snow[0]]=ns;changed++;}d.SetAlphamaps(0,0,a);EditorUtility.SetDirty(d);AssetDatabase.SaveAssetIfDirty(d);}
  foreach(var f in UnityEngine.Object.FindObjectsByType<MeshFilter>()){if(!f.name.StartsWith("Northern World Rock ")||!f.sharedMesh)continue;var m=f.sharedMesh;var v=m.vertices;var colors=m.colors;if(colors.Length!=v.Length)continue;for(int i=0;i<v.Length;i++){var p=f.transform.TransformPoint(v[i]);var t=ts.FirstOrDefault(a=>p.x>=a.transform.position.x-.01f&&p.x<=a.transform.position.x+512.01f&&p.z>=a.transform.position.z-.01f&&p.z<=a.transform.position.z+512.01f);if(!t)continue;var a=paints[t];int x=Mathf.Clamp((int)((p.x-t.transform.position.x)/512*a.GetLength(1)),0,a.GetLength(1)-1),z=Mathf.Clamp((int)((p.z-t.transform.position.z)/512*a.GetLength(0)),0,a.GetLength(0)-1);float snow=0;foreach(int k in snowLookup[t])snow+=a[z,x,k];colors[i].r=snow;}m.colors=colors;m.UploadMeshData(false);EditorUtility.SetDirty(m);AssetDatabase.SaveAssetIfDirty(m);}
  Directory.CreateDirectory(Root+"Realistic");File.WriteAllText(Root+"Realistic/snow_transitions.txt","blendedTexels="+changed+" roadLayerWeightsPreserved=True regionalBiomesRetained=True");Debug.Log("SNOW_TRANSITION_TEXELS="+changed);
 }
 public static void SnowTrees(string mode){
  if(Application.isPlaying)throw new Exception("Edit Mode required");var shader=Shader.Find("MMUnity/Accumulated Tree Snow");if(!shader||ShaderUtil.ShaderHasError(shader))throw new Exception("Snow shader unavailable");
  var ts=MMTerrainBranchContrast20261007.Tiles();var paint=ts.ToDictionary(t=>t,t=>t.terrainData.GetAlphamaps(0,0,t.terrainData.alphamapWidth,t.terrainData.alphamapHeight));var slots=ts.ToDictionary(t=>t,t=>SnowSlots(t.terrainData));
  string dir="Assets/World/WorldExtensions/Generated/TreeSnow20261007/";Directory.CreateDirectory(dir);var cache=new Dictionary<string,Material>();int trees=0,renderers=0;
  foreach(var tr in UnityEngine.Object.FindObjectsByType<Transform>()){if(!Tree(tr)||tr.GetComponentsInParent<Transform>().Skip(1).Any(Tree))continue;var p=tr.position;var t=ts.FirstOrDefault(a=>p.x>=a.transform.position.x&&p.x<a.transform.position.x+512&&p.z>=a.transform.position.z&&p.z<a.transform.position.z+512);if(!t)continue;var a=paint[t];int x=Mathf.Clamp((int)((p.x-t.transform.position.x)/512*a.GetLength(1)),0,a.GetLength(1)-1),z=Mathf.Clamp((int)((p.z-t.transform.position.z)/512*a.GetLength(0)),0,a.GetLength(0)-1);float snow=0;foreach(int k in slots[t])snow+=a[z,x,k];if(snow<.32f)continue;int level=snow>.65f?2:1;bool changed=false;
   foreach(var r in tr.GetComponentsInChildren<Renderer>(true)){var materials=r.sharedMaterials;for(int i=0;i<materials.Length;i++){var src=materials[i];if(!src||src.shader==shader)continue;var texture=src.HasProperty("_MainTex")?src.GetTexture("_MainTex"):null;if(!texture&&src.HasProperty("_BaseColorMap"))texture=src.GetTexture("_BaseColorMap");if(!texture)continue;string key=AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(src))+"_"+src.name+"_"+level; // Dictionary key may include embedded FBX submaterials.
    if(!cache.TryGetValue(key,out var m)){string safe=new string(src.name.Select(c=>char.IsLetterOrDigit(c)?c:'_').ToArray());string id=AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(src));string path=dir+safe+"_"+id+"_"+level+".mat";m=AssetDatabase.LoadAssetAtPath<Material>(path);if(!m){m=new Material(shader);m.name=safe+" Snow "+level;m.SetTexture("_MainTex",texture);m.SetTextureScale("_MainTex",src.HasProperty("_MainTex")?src.GetTextureScale("_MainTex"):Vector2.one);if(src.HasProperty("_Color"))m.SetColor("_Color",src.GetColor("_Color"));if(src.HasProperty("_BumpMap"))m.SetTexture("_BumpMap",src.GetTexture("_BumpMap"));if(src.HasProperty("_BumpScale"))m.SetFloat("_BumpScale",src.GetFloat("_BumpScale"));m.SetFloat("_Cutoff",src.HasProperty("_Cutoff")?src.GetFloat("_Cutoff"):.37f);string name=src.name.ToLower();m.SetFloat("_Foliage",name.Contains("trunk")||name.Contains("bark")||name.Contains("stump")||name.Contains("wood")?0:1);m.SetFloat("_SnowAmount",level==2?.95f:.68f);m.enableInstancing=true;AssetDatabase.CreateAsset(m,path);}cache[key]=m;}materials[i]=m;changed=true;}if(changed){r.sharedMaterials=materials;renderers++;}}
   if(changed)trees++;
  }
  foreach(var m in cache.Values.Distinct()){EditorUtility.SetDirty(m);AssetDatabase.SaveAssetIfDirty(m);}var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);Directory.CreateDirectory(Root+mode);File.WriteAllText(Root+mode+"/snow_trees.txt","trees="+trees+" renderers="+renderers+" materials="+cache.Count+" minimumGroundSnow=.32 shaderErrors=False");Capture(mode);Debug.Log("SNOW_TREES="+trees+" renderers="+renderers+" materials="+cache.Count);
 }
}
