using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/FloatingTreeCheck_20260920";
 string Key(Transform t)=>t.parent?Key(t.parent)+"/"+t.GetSiblingIndex():t.GetSiblingIndex().ToString();
 string P(Transform t)=>t.parent?P(t.parent)+"/"+t.name:t.name;
 string Asset(UnityEngine.Object o){if(!o)return "null";return GlobalObjectId.GetGlobalObjectIdSlow(o).ToString()+"|"+AssetDatabase.GetAssetPath(o);}
 HashSet<string> allowed=new HashSet<string>();
 string Snapshot(Scene s){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true))){string k=Key(t);Vector3 lp=t.localPosition;if(allowed.Contains(k))lp.y=0;rows.Add(k+"|"+lp.ToString("R")+"|"+new Vector2(t.position.x,t.position.z).ToString("R")+"|"+t.localRotation.ToString("R")+"|"+t.localScale.ToString("R")+"|"+t.gameObject.activeSelf);foreach(var r in t.GetComponents<Renderer>())rows.Add(k+"|R|"+r.enabled+"|"+r.shadowCastingMode+"|"+string.Join(";",r.sharedMaterials.Select(m=>Asset(m)+"|inst="+(m&&m.enableInstancing))));foreach(var mf in t.GetComponents<MeshFilter>())rows.Add(k+"|M|"+Asset(mf.sharedMesh));foreach(var l in t.GetComponents<LODGroup>())rows.Add(k+"|LOD|"+l.enabled+"|"+string.Join(";",l.GetLODs().Select(q=>q.screenRelativeTransitionHeight+":"+q.fadeTransitionWidth)));}return string.Join("\n",rows);}
 public void Execute(ExecutionResult result){string sp=File.ReadAllText(Out+"/apply_next.txt").Trim();string name=Path.GetFileNameWithoutExtension(sp);var rows=File.ReadAllLines(Out+"/floating_selected.tsv").Select(l=>l.Split('\t')).Where(p=>p.Length>=3&&p[0]==name).ToArray();var s=EditorSceneManager.OpenScene(sp,OpenSceneMode.Single);var all=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var targets=new List<System.Tuple<Transform,float>>();foreach(var p in rows){var mm=all.Where(t=>P(t)==p[1]).ToArray();if(mm.Length!=1)throw new Exception("Target matching="+mm.Length+" "+p[1]);var t=mm[0];targets.Add(System.Tuple.Create(t,float.Parse(p[2],System.Globalization.CultureInfo.InvariantCulture)));}
 allowed.Clear();foreach(var x in targets)allowed.Add(Key(x.Item1));string before=Snapshot(s);var log=new List<string>();foreach(var x in targets){var t=x.Item1;var old=t.position;var rot=t.localRotation;var sc=t.localScale;t.position=new Vector3(old.x,old.y-x.Item2,old.z);if(t.position.x!=old.x||t.position.z!=old.z||t.localRotation!=rot||t.localScale!=sc)throw new Exception("Non-Y change "+P(t));log.Add(P(t)+"|oldY="+old.y.ToString("R")+"|newY="+t.position.y.ToString("R")+"|lowered="+x.Item2.ToString("R"));}
 if(Snapshot(s)!=before)throw new Exception("Protected state changed "+name);if(targets.Count>0){EditorSceneManager.MarkSceneDirty(s);if(!EditorSceneManager.SaveScene(s))throw new Exception("Save failed");s=EditorSceneManager.OpenScene(sp,OpenSceneMode.Single);if(Snapshot(s)!=before)throw new Exception("Reload invariant "+name);}File.WriteAllLines(Out+"/"+name+"_confirmed_y_only.txt",log);result.Log(name+" confirmed floating fixed="+targets.Count+" onlyY=PASS");
 }
}