using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/CanalAudit_20260920";
 struct Pt{public int x,z;public Pt(int X,int Z){x=X;z=Z;}}
 bool WaterRenderer(Renderer r){if(!r.enabled||!r.gameObject.activeInHierarchy)return false;var mf=r.GetComponent<MeshFilter>();if(!mf||!mf.sharedMesh)return false;var m=r.sharedMaterial;string p=m?AssetDatabase.GetAssetPath(m):"";return p.EndsWith("UnifiedEnrothWater.mat",StringComparison.OrdinalIgnoreCase)&&!r.name.ToLowerInvariant().Contains("bottom")&&!r.name.ToLowerInvariant().Contains("seabed");}
 bool Inside(Vector2 p,Vector2 a,Vector2 b,Vector2 c){float d1=(p.x-b.x)*(a.y-b.y)-(a.x-b.x)*(p.y-b.y);float d2=(p.x-c.x)*(b.y-c.y)-(b.x-c.x)*(p.y-c.y);float d3=(p.x-a.x)*(c.y-a.y)-(c.x-a.x)*(p.y-a.y);bool neg=d1<-.0001f||d2<-.0001f||d3<-.0001f,pos=d1>.0001f||d2>.0001f||d3>.0001f;return !(neg&&pos);}
 public void Execute(ExecutionResult result){Directory.CreateDirectory(Out);string sp=File.ReadAllText(Out+"/next.txt").Trim();string name=Path.GetFileNameWithoutExtension(sp);var s=EditorSceneManager.OpenScene(sp,OpenSceneMode.Single);var ts=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var terr=ts.Select(t=>t.GetComponent<Terrain>()).FirstOrDefault(t=>t);if(!terr){File.WriteAllText(Out+"/"+name+".csv","scene,candidate\n");return;}var td=terr.terrainData;int N=td.heightmapResolution-1;var covered=new bool[N,N];var wr=ts.SelectMany(t=>t.GetComponents<Renderer>()).Where(WaterRenderer).ToArray();if(wr.Length==0){File.WriteAllText(Out+"/"+name+".csv","scene,candidate\n");result.Log(name+" no water renderer");return;}
 var waterYs=new List<float>();int tris=0;float csx=td.size.x/N,csz=td.size.z/N;foreach(var r in wr){waterYs.Add(r.bounds.center.y);var mf=r.GetComponent<MeshFilter>();var mesh=mf.sharedMesh;var v=mesh.vertices;for(int sm=0;sm<mesh.subMeshCount;sm++){var ix=mesh.GetIndices(sm);for(int i=0;i+2<ix.Length;i+=3){Vector3 aw=r.transform.TransformPoint(v[ix[i]]),bw=r.transform.TransformPoint(v[ix[i+1]]),cw=r.transform.TransformPoint(v[ix[i+2]]);Vector2 a=new Vector2(aw.x,aw.z),b=new Vector2(bw.x,bw.z),c=new Vector2(cw.x,cw.z);float minx=Mathf.Min(a.x,Mathf.Min(b.x,c.x)),maxx=Mathf.Max(a.x,Mathf.Max(b.x,c.x)),minz=Mathf.Min(a.y,Mathf.Min(b.y,c.y)),maxz=Mathf.Max(a.y,Mathf.Max(b.y,c.y));int x0=Mathf.Max(0,Mathf.FloorToInt((minx-terr.transform.position.x)/csx)-1),x1=Mathf.Min(N-1,Mathf.CeilToInt((maxx-terr.transform.position.x)/csx)+1),z0=Mathf.Max(0,Mathf.FloorToInt((minz-terr.transform.position.z)/csz)-1),z1=Mathf.Min(N-1,Mathf.CeilToInt((maxz-terr.transform.position.z)/csz)+1);for(int zz=z0;zz<=z1;zz++)for(int xx=x0;xx<=x1;xx++){Vector2 p=new Vector2(terr.transform.position.x+(xx+.5f)*csx,terr.transform.position.z+(zz+.5f)*csz);if(Inside(p,a,b,c))covered[xx,zz]=true;}tris++;}}}
 waterYs.Sort();float waterY=waterYs[waterYs.Count/2];var low=new bool[N,N];for(int z=0;z<N;z++)for(int x=0;x<N;x++){float u=(x+.5f)/N,v=(z+.5f)/N;float h=terr.transform.position.y+td.GetInterpolatedHeight(u,v);low[x,z]=h<waterY-.02f&&!covered[x,z];}
 int[,] wlab=new int[N,N];for(int z=0;z<N;z++)for(int x=0;x<N;x++)wlab[x,z]=-1;int wid=0;int[] dx={1,-1,0,0},dz={0,0,1,-1};for(int z=0;z<N;z++)for(int x=0;x<N;x++)if(covered[x,z]&&wlab[x,z]<0){var q=new Queue<Pt>();q.Enqueue(new Pt(x,z));wlab[x,z]=wid;while(q.Count>0){var p=q.Dequeue();for(int k=0;k<4;k++){int nx=p.x+dx[k],nz=p.z+dz[k];if(nx>=0&&nz>=0&&nx<N&&nz<N&&covered[nx,nz]&&wlab[nx,nz]<0){wlab[nx,nz]=wid;q.Enqueue(new Pt(nx,nz));}}}wid++;}
 var seen=new bool[N,N];var lines=new List<string>{"scene,id,cells,minX,maxX,minZ,maxZ,length_m,width_m,mean_width_m,waterY,water_components,contact_count,endpoint1_x,endpoint1_z,endpoint2_x,endpoint2_z,center_x,center_z,safe_no_building_road_check"};
 int cid=0,cands=0;for(int z=0;z<N;z++)for(int x=0;x<N;x++)if(low[x,z]&&!seen[x,z]){var q=new Queue<Pt>();var comp=new List<Pt>();q.Enqueue(new Pt(x,z));seen[x,z]=true;while(q.Count>0){var p=q.Dequeue();comp.Add(p);for(int k=0;k<4;k++){int nx=p.x+dx[k],nz=p.z+dz[k];if(nx>=0&&nz>=0&&nx<N&&nz<N&&low[nx,nz]&&!seen[nx,nz]){seen[nx,nz]=true;q.Enqueue(new Pt(nx,nz));}}}
 int minx=comp.Min(p=>p.x),maxx=comp.Max(p=>p.x),minz=comp.Min(p=>p.z),maxz=comp.Max(p=>p.z);float sx=td.size.x/N,sz=td.size.z/N;float len=Mathf.Max((maxx-minx+1)*sx,(maxz-minz+1)*sz);float widm=Mathf.Min((maxx-minx+1)*sx,(maxz-minz+1)*sz);float meanw=comp.Count/Mathf.Max(1f,Mathf.Max(maxx-minx+1,maxz-minz+1))*Mathf.Max(sx,sz);var contacts=new List<Pt>();var labs=new List<int>();foreach(var p in comp)for(int k=0;k<4;k++){int nx=p.x+dx[k],nz=p.z+dz[k];if(nx>=0&&nz>=0&&nx<N&&nz<N&&covered[nx,nz]){contacts.Add(new Pt(nx,nz));if(!labs.Contains(wlab[nx,nz]))labs.Add(wlab[nx,nz]);}}
 if(comp.Count<2||comp.Count>5000||len<3||meanw>12||labs.Count<2){cid++;continue;}float best=-1;Pt a=new Pt(),b=new Pt();for(int i=0;i<contacts.Count;i++)for(int j=i+1;j<contacts.Count;j++){if(wlab[contacts[i].x,contacts[i].z]==wlab[contacts[j].x,contacts[j].z])continue;float dd=(contacts[i].x-contacts[j].x)*(contacts[i].x-contacts[j].x)+(contacts[i].z-contacts[j].z)*(contacts[i].z-contacts[j].z);if(dd>best){best=dd;a=contacts[i];b=contacts[j];}}if(best<4){cid++;continue;}
 Func<Pt,Vector2> world=p=>new Vector2(terr.transform.position.x+(p.x+.5f)*sx,terr.transform.position.z+(p.z+.5f)*sz);Vector2 wa=world(a),wb=world(b);Vector2 cc=new Vector2(terr.transform.position.x+((float)comp.Average(p=>p.x)+.5f)*sx,terr.transform.position.z+((float)comp.Average(p=>p.z)+.5f)*sz);
 lines.Add(name+","+cid+","+comp.Count+","+minx+","+maxx+","+minz+","+maxz+","+len.ToString("F2")+","+widm.ToString("F2")+","+meanw.ToString("F2")+","+waterY.ToString("F3")+","+string.Join(";",labs.OrderBy(v=>v).Select(v=>v.ToString()).ToArray())+","+contacts.Count+","+wa.x.ToString("F2")+","+wa.y.ToString("F2")+","+wb.x.ToString("F2")+","+wb.y.ToString("F2")+","+cc.x.ToString("F2")+","+cc.y.ToString("F2")+",NOT_YET_CHECKED");cands++;cid++;}
 File.WriteAllLines(Out+"/"+name+".csv",lines);File.WriteAllText(Out+"/"+name+"_summary.txt","water_renderers="+wr.Length+"\nwater_components="+wid+"\ntriangles_sampled="+tris+"\ncandidates="+cands+"\nwaterY="+waterY.ToString("R")+"\n");result.Log(name+" canal candidates="+cands+" waterComponents="+wid);
 }
}