using System; using System.IO; using System.Linq; using System.Text; using System.Globalization; using System.Collections.Generic; using System.Security.Cryptography;
using UnityEngine; using UnityEditor; using UnityEditor.SceneManagement; using UnityEngine.SceneManagement;
internal class CommandScript : IRunCommand {
 const string Root="Validation/Coast17"; const string Backup="Backups/Coast17_20260919";
 string MeshPath(Renderer r){var mf=r.GetComponent<MeshFilter>();return mf?AssetDatabase.GetAssetPath(mf.sharedMesh):r is SkinnedMeshRenderer sk?AssetDatabase.GetAssetPath(sk.sharedMesh):"none";}
 string F(float x)=>x.ToString("R",CultureInfo.InvariantCulture);
 string V(Vector3 v)=>F(v.x)+","+F(v.y)+","+F(v.z);
 string Id(UnityEngine.Object o)=>o?GlobalObjectId.GetGlobalObjectIdSlow(o).ToString():"null";
 string Hash(IEnumerable<string> lines){using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(Encoding.UTF8.GetBytes(string.Join("\n",lines)))).Replace("-","");}
 string[] Snapshot(Scene s,HashSet<string> permitted){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true))){rows.Add("T|"+Id(t)+"|"+Id(t.parent)+"|"+V(t.localPosition)+"|"+t.localRotation.ToString("R")+"|"+V(t.localScale)+"|"+V(t.position)+"|"+t.gameObject.activeSelf+"|"+GameObjectUtility.GetStaticEditorFlags(t.gameObject));foreach(var r in t.GetComponents<Renderer>()){var text=EditorJsonUtility.ToJson(r);if(permitted.Contains(Id(r)))text=text.Replace("\"m_Enabled\":true","\"m_Enabled\":false").Replace("\"m_Enabled\":1","\"m_Enabled\":0");rows.Add("R|"+Id(r)+"|"+text);}foreach(var mf in t.GetComponents<MeshFilter>())rows.Add("M|"+Id(mf)+"|"+Id(mf.sharedMesh));foreach(var c in t.GetComponents<Collider>())rows.Add("C|"+Id(c)+"|"+EditorJsonUtility.ToJson(c));}rows.Sort(StringComparer.Ordinal);return rows.ToArray();}
 void Protect(bool[,] mask,Terrain t,Scene s){int n=mask.GetLength(0);float step=t.terrainData.size.x/(n-1);var origin=t.transform.position;
 foreach(var tr in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true))){if(tr.GetComponent<Terrain>()||IsWater(tr.name))continue;var p=tr.position-origin;int x=Mathf.RoundToInt(p.x/step),z=Mathf.RoundToInt(p.z/step);if(x<0||z<0||x>=n||z>=n)continue;int rad=Mathf.CeilToInt(2f/step);for(int j=Math.Max(0,z-rad);j<=Math.Min(n-1,z+rad);j++)for(int i=Math.Max(0,x-rad);i<=Math.Min(n-1,x+rad);i++)mask[j,i]=true;}
 foreach(var r in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true))){if(IsWater(r.name))continue;var b=r.bounds;if(b.min.y>.7f||b.size.x*b.size.z>5000)continue;int x0=Math.Max(0,Mathf.FloorToInt((b.min.x-origin.x-1)/step)),x1=Math.Min(n-1,Mathf.CeilToInt((b.max.x-origin.x+1)/step));int z0=Math.Max(0,Mathf.FloorToInt((b.min.z-origin.z-1)/step)),z1=Math.Min(n-1,Mathf.CeilToInt((b.max.z-origin.z+1)/step));for(int z=z0;z<=z1;z++)for(int x=x0;x<=x1;x++)mask[z,x]=true;}}
 bool IsWater(string n)=>n.StartsWith("Water -")||n=="Internal Water - Smooth"||n=="Unified Water Bottom"||n.StartsWith("Curved Seabed")||n=="Global Ocean Surface"||n=="Ocean + Central Lake Water";
 void Capture(Scene s,Terrain t,string path,Vector3 point){var go=new GameObject("__CoastAuditCamera");SceneManager.MoveGameObjectToScene(go,s);try{var c=go.AddComponent<Camera>();c.nearClipPlane=.1f;c.farClipPlane=5000;c.fieldOfView=55;c.depthTextureMode=DepthTextureMode.Depth;c.transform.position=point+new Vector3(32,25,-38);c.transform.LookAt(point);MMSequentialEvidence.Render(c,path+"_detail.png",960,720);c.orthographic=true;c.orthographicSize=t.terrainData.size.x*.55f;c.transform.position=t.transform.position+new Vector3(t.terrainData.size.x*.5f,800,t.terrainData.size.z*.5f);c.transform.rotation=Quaternion.Euler(90,0,0);MMSequentialEvidence.Render(c,path+"_top.png",800,800);}finally{UnityEngine.Object.DestroyImmediate(go);}}
 public void Execute(ExecutionResult result){
  for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");
  const string path="Assets/Scenes/World/Enroth.unity";var s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);string dir=Root+"/Enroth";Directory.CreateDirectory(dir);
  var ts=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Terrain>(true)).ToArray();var rs=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).ToArray();var redundant=rs.Where(r=>r.name=="Unified Water Bottom").ToArray();var allowed=new HashSet<string>(redundant.Select(r=>Id(r)));var before=Snapshot(s,allowed);string hash=Hash(before);File.WriteAllLines(dir+"/invariants_before.txt",before);File.WriteAllLines(dir+"/renderer_states.txt",rs.Select(r=>Id(r)+"|"+r.name+"|"+r.enabled+"|"+MeshPath(r)));
  if(!File.Exists(Backup+"/Enroth.unity"))File.Copy(path,Backup+"/Enroth.unity");
  long removed=0;int disabled=0;foreach(var r in redundant)if(r.enabled){var mesh=r.GetComponent<MeshFilter>().sharedMesh;for(int i=0;i<mesh.subMeshCount;i++)removed+=(long)mesh.GetIndexCount(i)/3;r.enabled=false;disabled++;}
  if(Hash(Snapshot(s,allowed))!=hash)throw new Exception("Linked invariant failed");
  if(disabled>0){EditorSceneManager.MarkSceneDirty(s);if(!EditorSceneManager.SaveScene(s))throw new Exception("Save failed");}
  s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var after=Snapshot(s,allowed);if(Hash(after)!=hash)throw new Exception("Linked saved invariant failed");File.WriteAllLines(dir+"/invariants_after.txt",after);
  ts=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Terrain>(true)).ToArray();
  var seams=new List<string>{"terrain_a,terrain_b,axis,max_height_gap_m,wet_wet_max_gap_m,wet_dry_disagreements,water_level_delta_m"};int seamCount=0;float worst=0;Vector3 worstPoint=Vector3.zero;
  foreach(var a in ts)foreach(var b in ts){if(a==b)continue;var pa=a.transform.position;var pb=b.transform.position;var size=a.terrainData.size;bool east=Mathf.Abs(pa.x+size.x-pb.x)<.01f&&Mathf.Abs(pa.z-pb.z)<.01f;bool north=Mathf.Abs(pa.z+size.z-pb.z)<.01f&&Mathf.Abs(pa.x-pb.x)<.01f;if(!east&&!north)continue;
   float max=0,wetmax=0;int disagreement=0;for(int i=0;i<=512;i++){float u=i/512f;float ya=pa.y+a.terrainData.GetInterpolatedHeight(east?1:u,east?u:1),yb=pb.y+b.terrainData.GetInterpolatedHeight(east?0:u,east?u:0);float gap=Mathf.Abs(ya-yb);max=Mathf.Max(max,gap);if(ya<.12f&&yb<.12f)wetmax=Mathf.Max(wetmax,gap);if((ya<.12f)!=(yb<.12f))disagreement++;if(gap>worst){worst=gap;worstPoint=pa+new Vector3(east?size.x:u*size.x,Mathf.Max(ya,yb)-pa.y,east?u*size.z:size.z);}}
   seams.Add(Path.GetFileName(AssetDatabase.GetAssetPath(a.terrainData))+","+Path.GetFileName(AssetDatabase.GetAssetPath(b.terrainData))+","+(east?"X":"Z")+","+F(max)+","+F(wetmax)+","+disagreement+",0");seamCount++;
  }
  File.WriteAllLines(dir+"/seams.csv",seams);
  var waterRows=new List<string>{"name,y,enabled,mesh"};foreach(var r in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).Where(r=>r.name.StartsWith("Water -")||r.name=="Internal Water - Smooth"||r.name=="Global Ocean Surface"||r.name=="Ocean + Central Lake Water"))waterRows.Add(r.name+","+F(r.bounds.center.y)+","+r.enabled+","+MeshPath(r));File.WriteAllLines(dir+"/water_levels.csv",waterRows);
  var camgo=new GameObject("__LinkedCoastAudit");SceneManager.MoveGameObjectToScene(camgo,s);try{var c=camgo.AddComponent<Camera>();c.depthTextureMode=DepthTextureMode.Depth;c.farClipPlane=10000;c.orthographic=true;c.orthographicSize=1700;c.transform.position=new Vector3(-100,4000,0);c.transform.rotation=Quaternion.Euler(90,0,0);MMSequentialEvidence.Render(c,dir+"/overview.png",1600,1000);c.orthographic=false;c.fieldOfView=55;c.transform.position=worstPoint+new Vector3(60,65,-70);c.transform.LookAt(worstPoint);MMSequentialEvidence.Render(c,dir+"/worst_existing_seam.png",1000,750);}finally{UnityEngine.Object.DestroyImmediate(camgo);}
  File.WriteAllText(dir+"/done.txt","hash_before="+hash+"\nhash_after="+Hash(after)+"\noverlay_renderers_disabled="+disabled+"\noverlay_triangles_disabled="+removed+"\ntriangles_added=0\nseams_checked="+seamCount+"\nmax_existing_seam_gap_m="+F(worst)+"\nterrain_edge_samples=unchanged_by_pass\n");
  result.Log("17/17 inspected; linked open; overlay renderers disabled="+disabled+"; invariant hash PASS; existing max terrain seam gap="+F(worst)+"m");
 }
}
