using System;using System.IO;using System.Linq;using System.Text;using System.Collections.Generic;using System.Security.Cryptography;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/FinalWorld";
 string Id(UnityEngine.Object o)=>o?GlobalObjectId.GetGlobalObjectIdSlow(o).ToString():"null";
 string PathOf(Transform t)=>t.parent?PathOf(t.parent)+"/"+t.name:t.name;
 uint Seed(string s){unchecked{uint h=2166136261;foreach(char c in s)h=(h^c)*16777619;return h;}}
 bool Bad(Renderer r){var f=r.GetComponent<MeshFilter>();var sk=r as SkinnedMeshRenderer;var m=f?f.sharedMesh:sk?sk.sharedMesh:null;string x=(r.name+"|"+(m?m.name:"")+"|"+AssetDatabase.GetAssetPath(m)).ToLowerInvariant();return x.Contains("pine_b")||x.Contains("pine_c");}
 Transform Anchor(Renderer r){for(var t=r.transform;t.parent;t=t.parent){string p=t.parent.name;if(p.StartsWith("Vegetation - Source Anchored")||p=="Trees"||p=="Shrubs"||p=="Green Trees and Bushes"||p=="Realistic Ecosystem Supplementary"||p=="Forest - Natural Sparse")return t;}return r.transform;}
 bool Under(Transform t,HashSet<Transform> set){for(;t;t=t.parent)if(set.Contains(t))return true;return false;}
 string Hash(Scene s,HashSet<Transform> targets){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).Where(t=>!Under(t,targets))){rows.Add(Id(t)+"|"+t.localPosition.ToString("R")+"|"+t.localRotation.ToString("R")+"|"+t.localScale.ToString("R")+"|"+t.gameObject.activeSelf);foreach(var r in t.GetComponents<Renderer>())rows.Add(Id(r)+EditorJsonUtility.ToJson(r));foreach(var f in t.GetComponents<MeshFilter>())rows.Add(Id(f)+Id(f.sharedMesh));}rows.Sort(StringComparer.Ordinal);using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(Encoding.UTF8.GetBytes(string.Join("\n",rows)))).Replace("-","");}
 public void Execute(ExecutionResult result){
  for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");
  string scenePath=File.ReadAllText(Out+"/next_pinebc.txt").Trim(),key=Path.GetFileNameWithoutExtension(scenePath);if(File.Exists(Out+"/"+key+"_pinebc_done.txt")){result.Log("Already done");return;}
  var s=EditorSceneManager.OpenScene(scenePath,OpenSceneMode.Single);var terrain=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Terrain>(true)).Single();var td=terrain.terrainData;string zone=Path.GetFileNameWithoutExtension(AssetDatabase.GetAssetPath(td)).Replace("Terrain","");
  byte[] tile=null,groups=null,sem=null;string dat="Assets/World/"+zone+"/Data/";if(File.Exists(dat+"tilemap_u8.bin")){tile=File.ReadAllBytes(dat+"tilemap_u8.bin");groups=File.ReadAllBytes(dat+"tile_groups_u8.bin");sem=File.ReadAllBytes(dat+"tile_semantics_u8.bin");}
  Func<Vector3,bool> desert=p=>{if(tile==null||groups==null||sem==null)return false;int x=Mathf.Clamp(Mathf.FloorToInt((p.x-terrain.transform.position.x)/4),0,127),z=Mathf.Clamp(127-Mathf.FloorToInt((p.z-terrain.transform.position.z)/4),0,127);byte raw=tile[z*128+x];return groups[raw]==2&&(sem[raw]&3)==0&&(zone=="Dragonsand"||zone=="Blackshire"||zone=="ParadiseValley"||zone=="HermitsIsle");};
  var bad=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).Where(r=>r.enabled&&r.gameObject.activeInHierarchy&&Bad(r)).ToArray();var targets=new HashSet<Transform>();foreach(var rr in bad)targets.Add(Anchor(rr));targets.RemoveWhere(a=>Under(a.parent,targets));var before=Hash(s,targets);var anchors=new Dictionary<string,Vector3>();foreach(var a in targets)anchors[Id(a)]=a.position;int replaced=0,removed=0;float maxGap=0;
  var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Environment/FinalWorldVegetation/fir_sapling.prefab");if(!prefab&&targets.Count>0)throw new Exception("Approved fir prefab missing");
  foreach(var a in targets){Vector3 p=a.position;var old=a.GetComponentsInChildren<Renderer>(true).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();float oldHeight=old.Length>0?old.Max(r=>r.bounds.max.y)-old.Min(r=>r.bounds.min.y):4f;foreach(var l in a.GetComponentsInChildren<LODGroup>(true))l.enabled=false;foreach(var r in a.GetComponentsInChildren<Renderer>(true))r.enabled=false;foreach(var c in a.GetComponentsInChildren<Collider>(true))c.enabled=false;
   if(desert(p)){removed++;continue;}uint seed=Seed(PathOf(a));var v=(GameObject)PrefabUtility.InstantiatePrefab(prefab,s);v.name="ApprovedReplacement_fir_sapling";v.transform.SetParent(a,false);a.rotation=Quaternion.Euler(0,a.eulerAngles.y,0);a.localScale=Vector3.one;float h=Mathf.Clamp(oldHeight,2.2f,11f)*(0.85f+(seed%300)/1000f);v.transform.rotation=Quaternion.Euler(0,(seed%36000)/100f,0);v.transform.localScale=Vector3.one*h;v.transform.position=p;var rs=v.GetComponentsInChildren<Renderer>(true).Where(r=>r.enabled).ToArray();Bounds b=rs[0].bounds;for(int i=1;i<rs.Length;i++)b.Encapsulate(rs[i].bounds);float ground=terrain.SampleHeight(p)+terrain.transform.position.y;v.transform.position+=Vector3.up*(ground-b.min.y);rs=v.GetComponentsInChildren<Renderer>(true).Where(r=>r.enabled).ToArray();b=rs[0].bounds;for(int i=1;i<rs.Length;i++)b.Encapsulate(rs[i].bounds);maxGap=Mathf.Max(maxGap,Mathf.Abs(b.min.y-ground));replaced++;
  }
  foreach(var a in targets){var q=anchors[Id(a)];if(a.position.x!=q.x||a.position.z!=q.z)throw new Exception("Anchor XZ moved");}
  if(Hash(s,targets)!=before||maxGap>.025f)throw new Exception("Invariant/grounding failed");
  int remain=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).Count(r=>r.enabled&&r.gameObject.activeInHierarchy&&Bad(r));if(remain>0)throw new Exception("Pine B/C remains "+remain);
  if(targets.Count>0){EditorSceneManager.MarkSceneDirty(s);if(!EditorSceneManager.SaveScene(s))throw new Exception("Save failed");}
  File.WriteAllText(Out+"/"+key+"_pinebc_done.txt","anchors="+targets.Count+"\nreplaced="+replaced+"\ndesert_removed="+removed+"\nremaining=0\nanchor_xz_changes=0\nmax_ground_gap="+maxGap+"\n");result.Log(key+" pineBC anchors="+targets.Count+" replaced="+replaced+" desert_removed="+removed);
 }
}