using System;using System.IO;using System.Linq;using System.Text;using System.Collections.Generic;using System.Security.Cryptography;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/FinalWorld",Backup="Backups/FinalWorldCleanup";
 string Id(UnityEngine.Object o)=>o?GlobalObjectId.GetGlobalObjectIdSlow(o).ToString():"null";
 string PathOf(Transform t)=>t.parent?PathOf(t.parent)+"/"+t.name:t.name;
 uint Seed(string s){unchecked{uint h=2166136261;foreach(char c in s)h=(h^c)*16777619;return h;}}
 bool Bad(Renderer r){var f=r.GetComponent<MeshFilter>();var sk=r as SkinnedMeshRenderer;var m=f?f.sharedMesh:sk?sk.sharedMesh:null;string x=(r.name+"|"+(m?m.name:"")+"|"+AssetDatabase.GetAssetPath(m)+"|"+string.Join(";",r.sharedMaterials.Select(a=>AssetDatabase.GetAssetPath(a)))).ToLowerInvariant();return x.Contains("searsia_lucida")||x.Contains("pine_00")||x.Contains("pine_d")||x.Contains("banyantree")||x.Contains("tree_small_02_lod1");}
 bool Shrub(Renderer r){string s=(PathOf(r.transform)).ToLowerInvariant();return s.Contains("shrub")||s.Contains("bush")||s.Contains("wuestenstrauch")||s.Contains("wüstenstrauch");}
 Transform Anchor(Renderer r){for(var t=r.transform;t.parent;t=t.parent){string p=t.parent.name;if(p.StartsWith("Vegetation - Source Anchored")||p=="Trees"||p=="Shrubs"||p=="Green Trees and Bushes"||p=="Realistic Ecosystem Supplementary"||p=="Forest - Natural Sparse")return t;}return r.transform;}
 bool Under(Transform t,HashSet<Transform> set){for(;t;t=t.parent)if(set.Contains(t))return true;return false;}
 string Hash(Scene s,HashSet<Transform> targets){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).Where(t=>!Under(t,targets))){rows.Add(Id(t)+"|"+t.localPosition.ToString("R")+"|"+t.localRotation.ToString("R")+"|"+t.localScale.ToString("R")+"|"+t.gameObject.activeSelf);foreach(var r in t.GetComponents<Renderer>())rows.Add(Id(r)+EditorJsonUtility.ToJson(r));foreach(var f in t.GetComponents<MeshFilter>())rows.Add(Id(f)+Id(f.sharedMesh));}rows.Sort(StringComparer.Ordinal);using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(Encoding.UTF8.GetBytes(string.Join("\n",rows)))).Replace("-","");}
 bool AnchorMoved(HashSet<Transform> targets,Dictionary<string,Vector3> anchors){foreach(var a in targets)if(a.position.x!=anchors[Id(a)].x||a.position.z!=anchors[Id(a)].z)return true;return false;}
 public void Execute(ExecutionResult result){for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");Directory.CreateDirectory(Backup);string path=File.ReadAllText(Out+"/next.txt").Trim();string key=Path.GetFileNameWithoutExtension(path);if(File.Exists(Out+"/"+key+"_done.txt")){result.Log("Already processed");return;}var s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var t=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Terrain>(true)).Single();var td=t.terrainData;string zone=Path.GetFileNameWithoutExtension(AssetDatabase.GetAssetPath(td)).Replace("Terrain","");string bpath=Backup+"/"+Path.GetFileName(path);if(!File.Exists(bpath))File.Copy(path,bpath);string tp=AssetDatabase.GetAssetPath(td);if(!File.Exists(Backup+"/"+Path.GetFileName(tp)))File.Copy(tp,Backup+"/"+Path.GetFileName(tp));
 byte[] tile=null,groups=null,sem=null;string dat="Assets/World/"+zone+"/Data/";if(File.Exists(dat+"tilemap_u8.bin")){tile=File.ReadAllBytes(dat+"tilemap_u8.bin");groups=File.ReadAllBytes(dat+"tile_groups_u8.bin");sem=File.ReadAllBytes(dat+"tile_semantics_u8.bin");}
 Func<Vector3,bool> desert=p=>{if(tile==null)return false;int x=Mathf.Clamp(Mathf.FloorToInt((p.x-t.transform.position.x)/4),0,127),z=Mathf.Clamp(127-Mathf.FloorToInt((p.z-t.transform.position.z)/4),0,127);byte raw=tile[z*128+x];return groups[raw]==2&&(sem[raw]&3)==0&&(zone=="Dragonsand"||zone=="Blackshire"||zone=="ParadiseValley"||zone=="HermitsIsle");};
 var rs=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();var targets=new HashSet<Transform>();var remove=new HashSet<Transform>();
 foreach(var r in rs){bool d=desert(r.transform.position);if((d&&Shrub(r))||Bad(r)||(zone=="DragonIsle"&&PathOf(r.transform).Contains("Forest -"))){var a=Anchor(r);targets.Add(a);if(d)remove.Add(a);}}
 targets.RemoveWhere(a=>Under(a.parent,targets));remove.RemoveWhere(a=>!targets.Contains(a));var before=Hash(s,targets);var anchors=new Dictionary<string,Vector3>();foreach(var a in targets)anchors[Id(a)]=a.position;var rows=new List<string>{"anchor,species,x,z,height,ground_gap"};int replaced=0,removed=0;float maxGap=0;
 foreach(var a in targets){var p=a.position;var old=a.GetComponentsInChildren<Renderer>(true).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();float oldHeight=old.Length>0?old.Max(r=>r.bounds.max.y)-old.Min(r=>r.bounds.min.y):4;
  foreach(var l in a.GetComponentsInChildren<LODGroup>(true))l.enabled=false;foreach(var r in a.GetComponentsInChildren<Renderer>(true))r.enabled=false;foreach(var c in a.GetComponentsInChildren<Collider>(true))c.enabled=false;
  if(remove.Contains(a)){removed++;continue;}
  uint seed=Seed(PathOf(a));string species="fir_sapling";if(zone=="DragonIsle")species=(seed%2==0?"island_tree_01":"island_tree_02");var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Environment/FinalWorldVegetation/"+species+".prefab");var v=(GameObject)PrefabUtility.InstantiatePrefab(prefab,s);v.name="ApprovedReplacement_"+species;v.transform.SetParent(a,false);
  a.rotation=Quaternion.Euler(0,a.eulerAngles.y,0);a.localScale=Vector3.one;v.transform.rotation=Quaternion.Euler(0,(seed%36000)/100f,0);float h=zone=="DragonIsle"?(seed%4==0?5f+seed%200/100f:1.5f+seed%150/100f):Mathf.Clamp(oldHeight,2.2f,11f)*(0.85f+(seed%300)/1000f);v.transform.localScale=Vector3.one*h;v.transform.position=p;var b=MMSequentialEvidence.BoundsOf(v);float ground=t.SampleHeight(p)+t.transform.position.y;v.transform.position+=Vector3.up*(ground-b.min.y);float gap=MMSequentialEvidence.BoundsOf(v).min.y-ground;maxGap=Mathf.Max(maxGap,Mathf.Abs(gap));
  foreach(var r in v.GetComponentsInChildren<Renderer>(true).Where(r=>r.enabled)){foreach(var m in r.sharedMaterials)if(!m||!m.shader||!m.shader.isSupported||!m.mainTexture||!m.enableInstancing)throw new Exception("Replacement material failed");if(Bad(r))throw new Exception("Rejected replacement");}
  rows.Add(a.name+","+species+","+p.x+","+p.z+","+h+","+gap);replaced++;
 }
 int details=0;if(tile!=null&&td.detailResolution>0){for(int layer=0;layer<td.detailPrototypes.Length;layer++){var ar=td.GetDetailLayer(0,0,td.detailWidth,td.detailHeight,layer);bool changed=false;for(int z=0;z<td.detailHeight;z++)for(int x=0;x<td.detailWidth;x++)if(ar[z,x]>0&&desert(t.transform.position+new Vector3((x+.5f)*td.size.x/td.detailWidth,0,(z+.5f)*td.size.z/td.detailHeight))){details+=ar[z,x];ar[z,x]=0;changed=true;}if(changed)td.SetDetailLayer(0,0,layer,ar);}}
 if(Hash(s,targets)!=before||AnchorMoved(targets,anchors)||maxGap>.025f)throw new Exception("Vegetation invariant/ground check failed");
 int remaining=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).Count(r=>r.enabled&&r.gameObject.activeInHierarchy&&Bad(r));if(remaining>0)throw new Exception("Rejected family remains visible: "+remaining);
 if(details>0){EditorUtility.SetDirty(td);AssetDatabase.SaveAssetIfDirty(td);}EditorSceneManager.MarkSceneDirty(s);if(!EditorSceneManager.SaveScene(s))throw new Exception("Save failed");File.WriteAllLines(Out+"/"+key+"_replacements.csv",rows);File.WriteAllText(Out+"/"+key+"_done.txt","replaced="+replaced+"\ndesert_anchors_hidden="+removed+"\ndesert_details_removed="+details+"\nremaining_rejected=0\nnon_target_hash="+before+"\nmax_ground_gap="+maxGap+"\nanchor_xz_changes=0\n");result.Log(key+" replacements="+replaced+" desert removals="+removed+" invariants=PASS");
 }
}



