using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/CanalApproval_20260920";
 struct P{public int x,z;public P(int X,int Z){x=X;z=Z;}}
 bool Inside(Vector2 p,Vector2 a,Vector2 b,Vector2 c){float d1=(p.x-b.x)*(a.y-b.y)-(a.x-b.x)*(p.y-b.y);float d2=(p.x-c.x)*(b.y-c.y)-(b.x-c.x)*(p.y-c.y);float d3=(p.x-a.x)*(c.y-a.y)-(c.x-a.x)*(p.y-a.y);bool neg=d1<0||d2<0||d3<0,pos=d1>0||d2>0||d3>0;return !(neg&&pos);}
 public void Execute(ExecutionResult result){
  Directory.CreateDirectory(Out);var s=EditorSceneManager.OpenScene("Assets/Scenes/FrozenHighlands_SourceGrid.unity",OpenSceneMode.Single);
  var terr=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Terrain>(true)).Single();var td=terr.terrainData;int N=td.heightmapResolution-1;float sx=td.size.x/N,sz=td.size.z/N;
  var r=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<MeshRenderer>(true)).First(x=>x.name=="Internal Water - Smooth");var m=r.GetComponent<MeshFilter>().sharedMesh;var v=m.vertices;var covered=new bool[N,N];
  for(int sm=0;sm<m.subMeshCount;sm++){var ix=m.GetIndices(sm);for(int i=0;i+2<ix.Length;i+=3){Vector3 aw=r.transform.TransformPoint(v[ix[i]]),bw=r.transform.TransformPoint(v[ix[i+1]]),cw=r.transform.TransformPoint(v[ix[i+2]]);Vector2 a=new Vector2(aw.x,aw.z),b=new Vector2(bw.x,bw.z),c=new Vector2(cw.x,cw.z);int x0=Mathf.Max(0,Mathf.FloorToInt((Mathf.Min(a.x,Mathf.Min(b.x,c.x))-terr.transform.position.x)/sx)-1),x1=Mathf.Min(N-1,Mathf.CeilToInt((Mathf.Max(a.x,Mathf.Max(b.x,c.x))-terr.transform.position.x)/sx)+1),z0=Mathf.Max(0,Mathf.FloorToInt((Mathf.Min(a.y,Mathf.Min(b.y,c.y))-terr.transform.position.z)/sz)-1),z1=Mathf.Min(N-1,Mathf.CeilToInt((Mathf.Max(a.y,Mathf.Max(b.y,c.y))-terr.transform.position.z)/sz)+1);for(int z=z0;z<=z1;z++)for(int x=x0;x<=x1;x++){var p=new Vector2(terr.transform.position.x+(x+.5f)*sx,terr.transform.position.z+(z+.5f)*sz);if(Inside(p,a,b,c))covered[x,z]=true;}}}
  float wy=r.bounds.center.y;var low=new bool[N,N];for(int z=0;z<N;z++)for(int x=0;x<N;x++){float h=terr.transform.position.y+td.GetInterpolatedHeight((x+.5f)/N,(z+.5f)/N);low[x,z]=h<wy-.02f&&!covered[x,z];}
  var seen=new bool[N,N];int[] dx={1,-1,0,0},dz={0,0,1,-1};var lines=new List<string>{"id,cells,len,width,meanWidth,contacts,maxContactSep,cx,cz,minx,maxx,minz,maxz,waterY"};int id=0;
  for(int z=0;z<N;z++)for(int x=0;x<N;x++)if(low[x,z]&&!seen[x,z]){var q=new Queue<P>();var c=new List<P>();q.Enqueue(new P(x,z));seen[x,z]=true;while(q.Count>0){var p=q.Dequeue();c.Add(p);for(int k=0;k<4;k++){int nx=p.x+dx[k],nz=p.z+dz[k];if(nx>=0&&nz>=0&&nx<N&&nz<N&&low[nx,nz]&&!seen[nx,nz]){seen[nx,nz]=true;q.Enqueue(new P(nx,nz));}}}
    var contacts=new List<P>();foreach(var p in c)for(int k=0;k<4;k++){int nx=p.x+dx[k],nz=p.z+dz[k];if(nx>=0&&nz>=0&&nx<N&&nz<N&&covered[nx,nz])contacts.Add(new P(nx,nz));}
    if(contacts.Count<2)continue;float best=0;for(int i=0;i<contacts.Count;i++)for(int j=i+1;j<contacts.Count;j++){float dd=Vector2.Distance(new Vector2(contacts[i].x,contacts[i].z),new Vector2(contacts[j].x,contacts[j].z));if(dd>best)best=dd;}
    int minx=c.Min(p=>p.x),maxx=c.Max(p=>p.x),minz=c.Min(p=>p.z),maxz=c.Max(p=>p.z);float len=Mathf.Max((maxx-minx+1)*sx,(maxz-minz+1)*sz),wid=Mathf.Min((maxx-minx+1)*sx,(maxz-minz+1)*sz),mw=c.Count/Mathf.Max(1f,Mathf.Max(maxx-minx+1,maxz-minz+1))*Mathf.Max(sx,sz);if(c.Count<4||len<6||mw>12||best*Mathf.Max(sx,sz)<6)continue;float cx=terr.transform.position.x+((float)c.Average(p=>p.x)+.5f)*sx,cz=terr.transform.position.z+((float)c.Average(p=>p.z)+.5f)*sz;lines.Add(string.Join(",",new[]{id.ToString(),c.Count.ToString(),len.ToString("F2"),wid.ToString("F2"),mw.ToString("F2"),contacts.Count.ToString(),(best*Mathf.Max(sx,sz)).ToString("F2"),cx.ToString("F2"),cz.ToString("F2"),(terr.transform.position.x+(minx+.5f)*sx).ToString("F2"),(terr.transform.position.x+(maxx+.5f)*sx).ToString("F2"),(terr.transform.position.z+(minz+.5f)*sz).ToString("F2"),(terr.transform.position.z+(maxz+.5f)*sz).ToString("F2"),wy.ToString("F3")}));id++;}
  File.WriteAllLines(Out+"/WhiteCap_candidates.csv",lines);result.Log("WhiteCap candidates="+(lines.Count-1));
 }
}