from pathlib import Path
import re
ED=Path(r'C:\MMUnityPort\Assets\Editor')
files=sorted(ED.glob('Build*OpenWorld.cs'))
files=[p for p in files if p.name not in {'BuildEnrothOpenWorld.cs','BuildEnrothFullWorld.cs'}]
old='''            var placement=PlacementFor(go.name);\n            if (placement!=null && b.size.y>0.15f)\n            {\n                float surface=WaterAffiliated(go.name)?0.12f:SampleTerrainY(terrain,b.center.x,b.center.z);\n                float desiredBase=surface+placement.sourceBaseOffset*objectScale;\n                go.transform.position+=Vector3.up*(desiredBase-b.min.y);\n                grounded++;\n                b=GetRendererBounds(go);\n            }'''
new='''            var placement=PlacementFor(go.name);\n            if (placement!=null && b.size.y>0.15f && WaterAffiliated(go.name))\n            {\n                float surface=0.12f;\n                float desiredBase=surface+placement.sourceBaseOffset*objectScale;\n                go.transform.position+=Vector3.up*(desiredBase-b.min.y);\n                grounded++;\n                b=GetRendererBounds(go);\n            }'''
for p in files:
 s=p.read_text(encoding='utf-8')
 if old in s: s=s.replace(old,new)
 s=s.replace('''        StampDryGroundUnderBuildings(terrain, group.transform);\n        Physics.SyncTransforms();''','''        grounded += GroundArchitectureClusters(terrain, group.transform);\n        AddArchitectureSolidCores(group.transform);\n        StampDryGroundUnderBuildings(terrain, group.transform);\n        Physics.SyncTransforms();''')
 p.write_text(s,encoding='utf-8')
print('grounding call patched',len(files))
helper=r'''    static bool OverlapXZ(Bounds a, Bounds b, float margin)\n    {\n        return a.min.x-margin<=b.max.x && a.max.x+margin>=b.min.x &&\n               a.min.z-margin<=b.max.z && a.max.z+margin>=b.min.z;\n    }\n\n    static List<List<GameObject>> ArchitectureClusters(Transform root)\n    {\n        var items=root.Cast<Transform>().Where(t=>!WaterAffiliated(t.name) && !t.name.StartsWith("SolidCore_",StringComparison.OrdinalIgnoreCase)).Select(t=>t.gameObject).ToList();\n        var result=new List<List<GameObject>>(); var used=new bool[items.Count];\n        for(int i=0;i<items.Count;i++) if(!used[i])\n        {\n            var group=new List<GameObject>(); var q=new Queue<int>(); q.Enqueue(i); used[i]=true;\n            while(q.Count>0)\n            {\n                int k=q.Dequeue(); group.Add(items[k]); var a=GetRendererBounds(items[k]);\n                for(int j=0;j<items.Count;j++) if(!used[j])\n                {\n                    var b=GetRendererBounds(items[j]);\n                    float d=Vector2.Distance(new Vector2(a.center.x,a.center.z),new Vector2(b.center.x,b.center.z));\n                    if(OverlapXZ(a,b,5f)||d<30f){used[j]=true;q.Enqueue(j);}\n                }\n            }\n            result.Add(group);\n        }\n        return result;\n    }\n'''
for p in files:
 s=p.read_text(encoding='utf-8')
 marker='    static float ArchitectureScaleFactor(string name, Bounds raw)'
 if 'static List<List<GameObject>> ArchitectureClusters' not in s: s=s.replace(marker,helper+'\n'+marker)
 p.write_text(s,encoding='utf-8')
print('cluster helper patched')
helper2=r'''    static int GroundArchitectureClusters(Terrain terrain, Transform root)\n    {\n        int moved=0;\n        foreach(var cluster in ArchitectureClusters(root))\n        {\n            Bounds b=GetRendererBounds(cluster[0]); for(int i=1;i<cluster.Count;i++) b.Encapsulate(GetRendererBounds(cluster[i]));\n            float[] ys={SampleTerrainY(terrain,b.center.x,b.center.z),SampleTerrainY(terrain,b.min.x,b.min.z),SampleTerrainY(terrain,b.max.x,b.min.z),SampleTerrainY(terrain,b.min.x,b.max.z),SampleTerrainY(terrain,b.max.x,b.max.z)};\n            Array.Sort(ys); float surface=ys[2]; float delta=surface-b.min.y;\n            foreach(var go in cluster){go.transform.position+=Vector3.up*delta;moved++;}\n        }\n        return moved;\n    }\n\n    static Material ArchitectureCoreMaterial()\n    {\n        string path=MatFolder+"/Buildings/ArchitectureCore.mat"; var m=AssetDatabase.LoadAssetAtPath<Material>(path);\n        if(!m){m=new Material(Shader.Find("Standard"));AssetDatabase.CreateAsset(m,path);}\n        m.color=new Color(.18f,.13f,.10f); m.SetFloat("_Glossiness",.03f); m.SetFloat("_Metallic",0f); EditorUtility.SetDirty(m); return m;\n    }\n\n    static void AddArchitectureSolidCores(Transform root)\n    {\n        var mat=ArchitectureCoreMaterial(); int n=0;\n        foreach(var cluster in ArchitectureClusters(root))\n        {\n            Bounds b=GetRendererBounds(cluster[0]); for(int i=1;i<cluster.Count;i++) b.Encapsulate(GetRendererBounds(cluster[i]));\n            if(b.size.x<3f||b.size.z<3f||b.size.x>48f||b.size.z>48f||b.size.y<2f||b.size.y>22f) continue;\n            var core=GameObject.CreatePrimitive(PrimitiveType.Cube); core.name="SolidCore_"+(n++); core.transform.SetParent(root,true);\n            core.transform.position=new Vector3(b.center.x,b.min.y+b.size.y*.43f,b.center.z);\n            core.transform.localScale=new Vector3(Mathf.Max(1f,b.size.x-1.4f),Mathf.Max(.8f,b.size.y*.76f),Mathf.Max(1f,b.size.z-1.4f));\n            core.GetComponent<MeshRenderer>().sharedMaterial=mat;\n        }\n        Debug.Log("ARCHITECTURE_SOLID_CORES "+n);\n    }\n'''
for p in files:
 s=p.read_text(encoding='utf-8')
 marker='    static float ArchitectureScaleFactor(string name, Bounds raw)'
 if 'static int GroundArchitectureClusters' not in s: s=s.replace(marker,helper2+'\n'+marker)
 p.write_text(s,encoding='utf-8')
print('grounding/core helpers patched')
