using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/FloatingTreeCheck_20260920/Baseline";
 string P(Transform t)=>t.parent?P(t.parent)+"/"+t.name:t.name;
 bool Container(string n)=>n.StartsWith("Vegetation - Source Anchored",StringComparison.OrdinalIgnoreCase)||n=="Realistic Ecosystem Supplementary"||n=="Trees"||n=="Forest - Natural Sparse"||n=="Green Trees and Bushes";
 bool Treeish(Transform a){foreach(var t in a.GetComponentsInChildren<Transform>(true)){string n=t.name.ToLowerInvariant();if(n.Contains("tree")||n.Contains("pine")||n.Contains("fir")||n.Contains("jacaranda")||n.Contains("quiver")||n.Contains("searsia")||n.Contains("approvedreplacement"))return true;foreach(var mf in t.GetComponents<MeshFilter>()){string p=(mf.sharedMesh?AssetDatabase.GetAssetPath(mf.sharedMesh):"").ToLowerInvariant();if(p.Contains("tree")||p.Contains("pine")||p.Contains("fir")||p.Contains("jacaranda")||p.Contains("quiver"))return true;}}return false;}
 string Family(Transform t){var ms=t.GetComponentsInChildren<MeshFilter>(true).Where(m=>m.sharedMesh).Select(m=>AssetDatabase.GetAssetPath(m.sharedMesh)+"#"+m.sharedMesh.name).Distinct().OrderBy(x=>x).ToArray();return string.Join(";",ms);}
 public void Execute(ExecutionResult result){Directory.CreateDirectory(Out);string sp=File.ReadAllText(Out+"/next.txt").Trim();string name=Path.GetFileNameWithoutExtension(sp);var s=EditorSceneManager.OpenScene(sp,OpenSceneMode.Single);var all=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var terrains=all.Select(t=>t.GetComponent<Terrain>()).Where(t=>t).ToArray();var lines=new List<string>();int checkedCount=0;
 foreach(var a in all.Where(t=>t.parent&&Container(t.parent.name)&&t.gameObject.activeInHierarchy&&Treeish(t)).Distinct()){var approved=a.GetComponentsInChildren<Transform>(true).FirstOrDefault(t=>t.name.StartsWith("ApprovedReplacement_",StringComparison.OrdinalIgnoreCase));var target=approved?approved:a;if(!target.gameObject.activeInHierarchy)continue;var rs=target.GetComponentsInChildren<Renderer>(true).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();if(rs.Length==0)continue;Vector3 p=target.position;var terr=terrains.FirstOrDefault(t=>p.x>=t.transform.position.x&&p.z>=t.transform.position.z&&p.x<=t.transform.position.x+t.terrainData.size.x&&p.z<=t.transform.position.z+t.terrainData.size.z);if(!terr)continue;float ground=terr.SampleHeight(p)+terr.transform.position.y;float bottom=rs.Min(r=>r.bounds.min.y);float gap=bottom-ground;string full=P(target);string rel=full.Substring(full.IndexOf('/')+1);lines.Add(name+"|"+full+"|"+rel+"|"+gap.ToString("R")+"|"+ground.ToString("R")+"|"+bottom.ToString("R")+"|"+p.y.ToString("R")+"|"+p.x.ToString("R")+"|"+p.z.ToString("R")+"|"+Family(target));checkedCount++;}
 File.WriteAllLines(Out+"/"+name+".txt",lines);result.Log(name+" audited="+checkedCount);
 }
}