using System;using System.IO;using System.Linq;using System.Text;using System.Collections.Generic;using System.Security.Cryptography;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/FloatingTreeCheck_20260920",Backup="Backups/FloatingTreeY_20260920";
 string Key(Transform t)=>t.parent?Key(t.parent)+"/"+t.GetSiblingIndex():t.GetSiblingIndex().ToString();
 string P(Transform t)=>t.parent?P(t.parent)+"/"+t.name:t.name;
 string Asset(UnityEngine.Object o){if(!o)return "null";return GlobalObjectId.GetGlobalObjectIdSlow(o).ToString()+"|"+AssetDatabase.GetAssetPath(o);}
 HashSet<string> allowed=new HashSet<string>();
 bool Container(string n)=>n.StartsWith("Vegetation - Source Anchored",StringComparison.OrdinalIgnoreCase)||n=="Realistic Ecosystem Supplementary"||n=="Trees"||n=="Forest - Natural Sparse"||n=="Green Trees and Bushes";
 bool Treeish(Transform a){foreach(var t in a.GetComponentsInChildren<Transform>(true)){string n=t.name.ToLowerInvariant();if(n.Contains("tree")||n.Contains("pine")||n.Contains("fir")||n.Contains("jacaranda")||n.Contains("quiver")||n.Contains("searsia")||n.Contains("approvedreplacement"))return true;foreach(var mf in t.GetComponents<MeshFilter>()){string p=(mf.sharedMesh?AssetDatabase.GetAssetPath(mf.sharedMesh):"").ToLowerInvariant();if(p.Contains("tree")||p.Contains("pine")||p.Contains("fir")||p.Contains("jacaranda")||p.Contains("quiver"))return true;}}return false;}
 string Snapshot(Scene s){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true))){string k=Key(t);Vector3 lp=t.localPosition;if(allowed.Contains(k))lp.y=0;rows.Add(k+"|"+lp.ToString("R")+"|"+new Vector2(t.position.x,t.position.z).ToString("R")+"|"+t.localRotation.ToString("R")+"|"+t.localScale.ToString("R")+"|"+t.gameObject.activeSelf);foreach(var r in t.GetComponents<Renderer>())rows.Add(k+"|R|"+r.enabled+"|"+r.shadowCastingMode+"|"+string.Join(";",r.sharedMaterials.Select(m=>Asset(m)+"|inst="+(m&&m.enableInstancing))));foreach(var mf in t.GetComponents<MeshFilter>())rows.Add(k+"|M|"+Asset(mf.sharedMesh));foreach(var l in t.GetComponents<LODGroup>())rows.Add(k+"|LOD|"+l.enabled+"|"+string.Join(";",l.GetLODs().Select(q=>q.screenRelativeTransitionHeight+":"+q.fadeTransitionWidth)));}return string.Join("\n",rows);}
 public void Execute(ExecutionResult result){Directory.CreateDirectory(Out);string sp=File.ReadAllText(Out+"/next.txt").Trim();string name=Path.GetFileNameWithoutExtension(sp);var s=EditorSceneManager.OpenScene(sp,OpenSceneMode.Single);var all=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var terrains=all.Select(t=>t.GetComponent<Terrain>()).Where(t=>t).ToArray();var roots=all.Where(t=>t.parent&&Container(t.parent.name)&&t.gameObject.activeInHierarchy&&Treeish(t)).Distinct().ToArray();var fixes=new List<System.Tuple<Transform,float,float,float,float>>();
 foreach(var a in roots){var approved=a.GetComponentsInChildren<Transform>(true).FirstOrDefault(t=>t.name.StartsWith("ApprovedReplacement_",StringComparison.OrdinalIgnoreCase));var target=approved?approved:a;if(!target.gameObject.activeInHierarchy)continue;var rs=target.GetComponentsInChildren<Renderer>(true).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();if(rs.Length==0)continue;Vector3 p=target.position;var terr=terrains.FirstOrDefault(t=>p.x>=t.transform.position.x&&p.z>=t.transform.position.z&&p.x<=t.transform.position.x+t.terrainData.size.x&&p.z<=t.transform.position.z+t.terrainData.size.z);if(!terr)continue;float ground=terr.SampleHeight(p)+terr.transform.position.y;float bottom=rs.Min(r=>r.bounds.min.y);float gap=bottom-ground;if(gap>.10f)fixes.Add(System.Tuple.Create(target,gap,p.y,p.x,p.z));}
 allowed.Clear();foreach(var f in fixes)allowed.Add(Key(f.Item1));string before=Snapshot(s);var lines=new List<string>();foreach(var f in fixes){var t=f.Item1;Vector3 old=t.position;Quaternion rot=t.localRotation;Vector3 sc=t.localScale;t.position=new Vector3(old.x,old.y-f.Item2,old.z);if(t.position.x!=old.x||t.position.z!=old.z||t.localRotation!=rot||t.localScale!=sc)throw new Exception("Non-Y change "+P(t));lines.Add(P(t)+"|relative="+P(t).Substring(P(t).IndexOf('/')+1)+"|oldY="+old.y.ToString("R")+"|newY="+t.position.y.ToString("R")+"|gap="+f.Item2.ToString("R")+"|x="+old.x.ToString("R")+"|z="+old.z.ToString("R"));}
 if(Snapshot(s)!=before)throw new Exception("Protected state changed "+name);
 if(fixes.Count>0){Directory.CreateDirectory(Backup);string bak=Backup+"/"+Path.GetFileName(sp);if(!File.Exists(bak))File.Copy(sp,bak);EditorSceneManager.MarkSceneDirty(s);if(!EditorSceneManager.SaveScene(s))throw new Exception("Save failed");s=EditorSceneManager.OpenScene(sp,OpenSceneMode.Single);if(Snapshot(s)!=before)throw new Exception("Reload invariant "+name);}
 File.WriteAllLines(Out+"/"+name+"_floating_y.txt",lines);File.WriteAllText(Out+"/"+name+"_done.txt","tree_roots_checked="+roots.Length+"\nfloating_fixed="+fixes.Count+"\nonly_y_changed=PASS\nprotected_state=PASS\n");result.Log(name+" checked="+roots.Length+" fixed="+fixes.Count);
 }
}