from pathlib import Path
s=Path('Tools/StructuralGroundFinalize.cs').read_text(); head=s[:s.index('public void Execute')]
bad=Path('Tools/StructuralVisualQA.cs').read_text();bad=bad[bad.index(' bool Bad'):bad.index(' public void Execute')]
body=r'''
public void Execute(ExecutionResult result){
for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");var report=new List<string>{"scene,missing_prefabs,rejected_visible,broken_materials,open_errors,open_warnings,protected_state"};
foreach(var path in Directory.GetFiles("Assets/Scenes","*.unity").Where(p=>!Path.GetFileName(p).StartsWith("_Recovery_")).OrderBy(p=>p.Contains("Enroth_Linked")?1:0).ThenBy(p=>p)){
int errors=0,warnings=0;Application.LogCallback cb=(m,st,t)=>{if(t==LogType.Warning)warnings++;if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors++;};Application.logMessageReceived+=cb;Scene s;try{s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);}finally{Application.logMessageReceived-=cb;}var ts=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var rs=ts.SelectMany(t=>t.GetComponents<Renderer>()).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();int missing=ts.Count(t=>PrefabUtility.GetPrefabInstanceStatus(t.gameObject)==PrefabInstanceStatus.MissingAsset),badCount=rs.Count(Bad),broken=rs.Count(r=>r.sharedMaterials.Any(m=>!m||!m.shader||!m.shader.isSupported||m.shader.name.Contains("InternalErrorShader")));
allowed.Clear();string state="PASS";
if(!s.name.Contains("Enroth_Linked")){if(s.name=="MireOfTheDamned_SourceGrid"){var paths=File.ReadAllLines(Out+"/"+s.name+"_ground_corrections.txt").Select(l=>l.Split('|')[0]).ToArray();foreach(var t in ts.Where(t=>paths.Contains(PathOf(t))))allowed.Add(Key(t));}
var original=File.ReadAllLines(Out+"/"+s.name+"_after.txt");for(int j=0;j<original.Length;j++){var f=original[j].Split('|');if(f[1].StartsWith("(")){var local=Parse(f[1]);if(allowed.Contains(f[0]))local.y=0;var world=Parse(f[2]);f[1]=local.ToString("R");f[2]=new Vector2(world.x,world.z).ToString("R");original[j]=string.Join("|",f);}}
if(string.Join("\n",original)!=Snapshot(s)){state="FAIL";File.WriteAllText(Out+"/"+s.name+"_final_snapshot.txt",Snapshot(s));}
}
report.Add(s.name+","+missing+","+badCount+","+broken+","+errors+","+warnings+","+state);File.WriteAllLines(Out+"/final_audit.csv",report);if(missing+badCount+broken+errors+warnings>0||state=="FAIL")throw new Exception("Final check failed: "+report.Last());
if(s.name=="MireOfTheDamned_SourceGrid"){var terrain=ts.Select(t=>t.GetComponent<Terrain>()).First(t=>t);foreach(string anchor in new[]{"Eco_GREEN_4_50","Eco_GREEN_8_34","SourceTree_0285_6tree13"}){var t=ts.First(a=>a.name==anchor);var target=t.position;target.y=terrain.SampleHeight(target)+terrain.transform.position.y+2;var go=new GameObject("QA Camera");var c=go.AddComponent<Camera>();c.farClipPlane=2000;c.fieldOfView=50;c.transform.position=target+new Vector3(12,5,-12);c.transform.LookAt(target);MMSequentialEvidence.Render(c,Out+"/grounded_"+anchor+".png",1000,800);UnityEngine.Object.DestroyImmediate(go);}}
if(s.name.Contains("Enroth_Linked")){var terrains=ts.Select(t=>t.GetComponent<Terrain>()).Where(t=>t).ToArray();float max=0;int pairs=0;foreach(var a in terrains)foreach(var b in terrains){var ap=a.transform.position;var bp=b.transform.position;int n=a.terrainData.heightmapResolution;if(Mathf.Abs(ap.x+a.terrainData.size.x-bp.x)<.001f&&Mathf.Abs(ap.z-bp.z)<.001f){pairs++;for(int k=0;k<n;k++)max=Mathf.Max(max,Mathf.Abs(ap.y+a.terrainData.GetHeight(n-1,k)-bp.y-b.terrainData.GetHeight(0,k)));}if(Mathf.Abs(ap.z+a.terrainData.size.z-bp.z)<.001f&&Mathf.Abs(ap.x-bp.x)<.001f){pairs++;for(int k=0;k<n;k++)max=Mathf.Max(max,Mathf.Abs(ap.y+a.terrainData.GetHeight(k,n-1)-bp.y-b.terrainData.GetHeight(k,0)));}}File.WriteAllText(Out+"/final_seams.txt","neighbor_pairs="+pairs+"\nmax_gap_m="+max+"\n");}
}
result.Log("16/16 + linked final verification PASS");}}
'''
Path('Tools/StructuralFinalVerify.cs').write_text(head+bad+body)
