from pathlib import Path
s=Path('Tools/VisualRefinementMaterials.cs').read_text();head=s[:s.index('public void Execute')]
bad=Path('Tools/StructuralVisualQA.cs').read_text();bad=bad[bad.index(' bool Bad'):bad.index(' public void Execute')].replace('PathOf(', 'PathOf(')
body=r'''
public void Execute(ExecutionResult result){for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");var report=new List<string>{"scene,missing_prefabs,rejected_visible,material_errors,open_errors,open_warnings,protected_state"};foreach(var path in Directory.GetFiles("Assets/Scenes","*.unity").Where(p=>!Path.GetFileName(p).StartsWith("_Recovery_")).OrderBy(p=>p.Contains("Enroth_Linked")?1:0).ThenBy(p=>p)){
int errors=0,warnings=0;Application.LogCallback cb=(m,st,t)=>{if(t==LogType.Warning)warnings++;if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors++;};Application.logMessageReceived+=cb;Scene s;try{s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);}finally{Application.logMessageReceived-=cb;}var ts=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var rs=ts.SelectMany(t=>t.GetComponents<Renderer>()).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();int missing=ts.Count(t=>PrefabUtility.GetPrefabInstanceStatus(t.gameObject)==PrefabInstanceStatus.MissingAsset),badCount=rs.Count(Bad),broken=rs.Count(r=>r.sharedMaterials.Any(m=>!m||!m.shader||!m.shader.isSupported||m.shader.name.Contains("InternalErrorShader")));materialTargets.Clear();string baseline;
if(!s.name.Contains("Enroth_Linked")){var paths=new HashSet<string>();foreach(var f in Directory.GetFiles(Out,s.name+"*_material_changes.txt"))foreach(var line in File.ReadAllLines(f))paths.Add(line.Split('|')[0]);foreach(var t in ts)if(paths.Contains(PathOf(t)))materialTargets.Add(Key(t));baseline=Out+"/"+s.name+(s.name=="Blackshire_SourceGrid"?"_initial":"")+"_protected_before.txt";}
else{baseline=Out+"/linked_protected_before.txt";foreach(var line in File.ReadAllLines(baseline))if(line.Contains("|R|")&&line.Contains("approved-material"))materialTargets.Add(line.Split('|')[0]);}
var original=File.ReadAllLines(baseline);for(int j=0;j<original.Length;j++){var f=original[j].Split('|');if(f.Length>9&&f[1]=="R"&&materialTargets.Contains(f[0])){string prefix=string.Join("|",f.Take(9));string tail=string.Join("|",f.Skip(9));tail=string.Join(";",tail.Split(';').Select(m=>"approved-material"+m.Substring(m.LastIndexOf("|instancing=",StringComparison.Ordinal))));original[j]=prefix+"|"+tail;}}
string state=string.Join("\n",original)==Snapshot(s)?"PASS":"FAIL";report.Add(s.name+","+missing+","+badCount+","+broken+","+errors+","+warnings+","+state);File.WriteAllLines(Out+"/final_audit.csv",report);if(missing+badCount+broken+errors+warnings>0||state=="FAIL"){File.WriteAllText(Out+"/"+s.name+"_failed_snapshot.txt",Snapshot(s));throw new Exception("Final check failed: "+report.Last());}
if(s.name.Contains("Enroth_Linked")){var terrains=ts.Select(t=>t.GetComponent<Terrain>()).Where(t=>t).ToArray();float max=0;int pairs=0;foreach(var a in terrains)foreach(var b in terrains){var ap=a.transform.position;var bp=b.transform.position;int n=a.terrainData.heightmapResolution;if(Mathf.Abs(ap.x+a.terrainData.size.x-bp.x)<.001f&&Mathf.Abs(ap.z-bp.z)<.001f){pairs++;for(int k=0;k<n;k++)max=Mathf.Max(max,Mathf.Abs(ap.y+a.terrainData.GetHeight(n-1,k)-bp.y-b.terrainData.GetHeight(0,k)));}if(Mathf.Abs(ap.z+a.terrainData.size.z-bp.z)<.001f&&Mathf.Abs(ap.x-bp.x)<.001f){pairs++;for(int k=0;k<n;k++)max=Mathf.Max(max,Mathf.Abs(ap.y+a.terrainData.GetHeight(k,n-1)-bp.y-b.terrainData.GetHeight(k,0)));}}File.WriteAllText(Out+"/final_seams.txt","neighbor_pairs="+pairs+"\nmax_gap_m="+max+"\n");if(max!=0)throw new Exception("Terrain seam changed");}
}result.Log("17 scenes verified; linked open; protected state PASS");}}
'''
Path('Tools/VisualRefinementVerify.cs').write_text(head+bad+body)
