from pathlib import Path
s=Path('Tools/StructuralCleanup.cs').read_text();head=s[:s.index(' public void Execute')].replace('Validation/StructuralQA','Validation/VisualRefinement').replace('Backups/StructuralCleanup_20260920','Backups/VisualRefinement_20260920')
head=head.replace('string Snapshot(Scene s)', 'HashSet<string> materialTargets=new HashSet<string>();\n string Snapshot(Scene s)').replace('m=>Asset(m)+"|instancing="+(m&&m.enableInstancing)','m=>(materialTargets.Contains(key)?"approved-material":Asset(m))+"|instancing="+(m&&m.enableInstancing)')
body=r'''
public void Execute(ExecutionResult result){for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");string path=File.ReadAllText(Out+"/next.txt").Trim();var s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var rs=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();var fixes=new Dictionary<Renderer,Material[]>();foreach(var r in rs){var f=r.GetComponent<MeshFilter>();if(!f||!f.sharedMesh)continue;string family=f.sharedMesh.name.Contains("island_tree_02")?"island_tree_02":f.sharedMesh.name.Contains("island_tree_01")?"island_tree_01":null;if(family==null||!r.sharedMaterials.Any(m=>AssetDatabase.GetAssetPath(m).StartsWith("Assets/Materials/RealisticWorld/IslandTree")))continue;var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Environment/FinalWorldVegetation/"+family+".prefab");var approved=prefab.GetComponentsInChildren<Renderer>(true).First(a=>a.enabled);if(approved.sharedMaterials.Length!=f.sharedMesh.subMeshCount)throw new Exception("Submesh mismatch");foreach(var m in approved.sharedMaterials)if(!m||!m.mainTexture||!m.enableInstancing||!m.shader.isSupported)throw new Exception("Approved material invalid");fixes[r]=approved.sharedMaterials;materialTargets.Add(Key(r.transform));}
string before=Snapshot(s);File.WriteAllText(Out+"/"+s.name+"_protected_before.txt",before);var rows=new List<string>();foreach(var fix in fixes){rows.Add(PathOf(fix.Key.transform)+"|"+string.Join(";",fix.Value.Select(m=>AssetDatabase.GetAssetPath(m))));fix.Key.sharedMaterials=fix.Value;}if(Snapshot(s)!=before)throw new Exception("Protected state changed");if(fixes.Count>0){Directory.CreateDirectory(Backup);if(!File.Exists(Backup+"/"+Path.GetFileName(path)))File.Copy(path,Backup+"/"+Path.GetFileName(path));EditorSceneManager.MarkSceneDirty(s);EditorSceneManager.SaveScene(s);s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);if(Snapshot(s)!=before)throw new Exception("Reload mismatch");}File.WriteAllLines(Out+"/"+s.name+"_material_changes.txt",rows);File.WriteAllText(Out+"/"+s.name+"_done.txt","corrected_material_renderers="+fixes.Count+"\nprotected_hash="+Hash(before)+"\nprotected_state=PASS\n");result.Log(s.name+" materials corrected="+fixes.Count+" protected state PASS");}}
'''
Path('Tools/VisualRefinementMaterials.cs').write_text(head+body)
s=Path('Tools/VisualRefinementCapture.cs').read_text().replace('"_before_"','"_"+File.ReadAllText("Validation/VisualRefinement/stage.txt").Trim()+"_"');Path('Tools/VisualRefinementCapture.cs').write_text(s)
Path('Validation/VisualRefinement/stage.txt').write_text('after')
