from pathlib import Path
s=Path('Tools/VisualRefinementMaterials.cs').read_text();head=s[:s.index('public void Execute')]
body=r'''
void Capture(Renderer r,string name){var b=r.bounds;var go=new GameObject("__LinkedVisualQA");var c=go.AddComponent<Camera>();c.fieldOfView=50;c.transform.position=b.center+new Vector3(b.size.y*.7f,0,-b.size.y*.8f);c.transform.LookAt(b.center);MMSequentialEvidence.Render(c,Out+"/"+name+".png",900,900);UnityEngine.Object.DestroyImmediate(go);}
public void Execute(ExecutionResult result){for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");var s=EditorSceneManager.OpenScene("Assets/Scenes/Enroth_Linked_OpenWorld.unity",OpenSceneMode.Single);var rs=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).ToArray();var fixes=new Dictionary<Renderer,Material[]>();var rows=new Dictionary<string,string>();foreach(var file in Directory.GetFiles(Out,"*_material_changes.txt"))foreach(var line in File.ReadAllLines(file)){var parts=line.Split('|');rows[parts[0]]=parts[1];}
foreach(var row in rows){int idx=row.Key.IndexOf('/');string root=row.Key.Substring(0,idx).Split(new[]{" - "},StringSplitOptions.None)[0];string relative=row.Key.Substring(idx);var match=rs.Where(r=>PathOf(r.transform).IndexOf("/"+root+" - ",StringComparison.OrdinalIgnoreCase)>=0&&PathOf(r.transform).EndsWith(relative,StringComparison.Ordinal)).ToArray();if(match.Length!=1)throw new Exception("Linked matching="+match.Length+" "+row.Key);var mats=row.Value.Split(';').Select(p=>AssetDatabase.LoadAssetAtPath<Material>(p)).ToArray();if(mats.Any(m=>!m||!m.enableInstancing))throw new Exception("Invalid material");fixes[match[0]]=mats;materialTargets.Add(Key(match[0].transform));}
var pine=fixes.Keys.FirstOrDefault(r=>r.name=="Pine_A_LOD0"&&PathOf(r.transform).Contains("Bootleg"));var dead=fixes.Keys.FirstOrDefault(r=>r.name=="PineDead_03_LOD0"&&PathOf(r.transform).Contains("Sweet"));if(pine)Capture(pine,"linked_pine_before");if(dead)Capture(dead,"linked_dead_before");string before=Snapshot(s);File.WriteAllText(Out+"/linked_protected_before.txt",before);foreach(var fix in fixes)fix.Key.sharedMaterials=fix.Value;if(Snapshot(s)!=before)throw new Exception("Linked invariant failed");Directory.CreateDirectory(Backup);if(!File.Exists(Backup+"/Enroth_Linked_OpenWorld.unity"))File.Copy(s.path,Backup+"/Enroth_Linked_OpenWorld.unity");EditorSceneManager.MarkSceneDirty(s);EditorSceneManager.SaveScene(s);if(pine)Capture(pine,"linked_pine_after");if(dead)Capture(dead,"linked_dead_after");s=EditorSceneManager.OpenScene(s.path,OpenSceneMode.Single);if(Snapshot(s)!=before)throw new Exception("Linked reload failed");int parity=0;rs=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).ToArray();foreach(var row in rows){int idx=row.Key.IndexOf('/');string root=row.Key.Substring(0,idx).Split(new[]{" - "},StringSplitOptions.None)[0];string relative=row.Key.Substring(idx);var r=rs.Single(a=>PathOf(a.transform).IndexOf("/"+root+" - ",StringComparison.OrdinalIgnoreCase)>=0&&PathOf(a.transform).EndsWith(relative,StringComparison.Ordinal));if(string.Join(";",r.sharedMaterials.Select(m=>AssetDatabase.GetAssetPath(m)))!=row.Value)throw new Exception("Material parity failed");parity++;}File.WriteAllText(Out+"/linked_done.txt","matched_renderers="+parity+"\nprotected_hash="+Hash(before)+"\nprotected_state=PASS\nmaterial_parity=PASS\n");result.Log("Linked material parity="+parity+" protected state PASS");}}
'''
Path('Tools/VisualLinkedSync.cs').write_text(head+body)
