from pathlib import Path
p=Path(r'C:\MMUnityPort\Assets\Editor\BuildNewSorpigalOpenWorld.cs')
s=p.read_text(encoding='utf-8')
a=s.index('    static GameObject BuildRiverBanks(Transform parent,Terrain terrain)')
b=s.index('    static GameObject BuildWater(Transform parent,Terrain terrain,Material unused)')
new='''    static GameObject BuildRiverBanks(Transform parent,Terrain terrain)\n    {\n        const int segs=560; var verts=new List<Vector3>((segs+1)*6); var uvs=new List<Vector2>((segs+1)*6); var tris=new List<int>(segs*24);\n        for(int i=0;i<=segs;i++)\n        {\n            float sy=Mathf.Lerp(103f,58f,i/(float)segs),cx=RiverCenterX(sy);\n            float sy0=Mathf.Max(58f,sy-.06f),sy1=Mathf.Min(103f,sy+.06f),cx0=RiverCenterX(sy0),cx1=RiverCenterX(sy1);\n            Vector2 p0=new Vector2((64f-cx0)*Cell,(sy0-64f)*Cell),p1=new Vector2((64f-cx1)*Cell,(sy1-64f)*Cell);\n            Vector2 tangent=(p0-p1).normalized,perp=new Vector2(-tangent.y,tangent.x),c=new Vector2((64f-cx)*Cell,(sy-64f)*Cell);\n            float hw=RiverHalfWidthWorld(sy),d=RiverDownstream01(sy);\n            float lb=Mathf.Lerp(2.2f,5.0f,d)*Mathf.Lerp(.84f,1.20f,Mathf.PerlinNoise(sy*.16f+2.7f,5.1f));\n            float rb=Mathf.Lerp(2.3f,4.8f,d)*Mathf.Lerp(.84f,1.20f,Mathf.PerlinNoise(sy*.14f+8.9f,1.4f));\n            Vector2 li=c+perp*(hw-.08f),lm=c+perp*(hw+lb*.46f),lo=c+perp*(hw+lb);\n            Vector2 ri=c-perp*(hw-.08f),rm=c-perp*(hw+rb*.46f),ro=c-perp*(hw+rb);\n            float iy=RiverSurfaceY(sy)+.055f;\n            float lmy=Mathf.Max(iy+.035f,SampleTerrainY(terrain,lm.x,lm.y)+.085f),loy=Mathf.Max(iy+.05f,SampleTerrainY(terrain,lo.x,lo.y)+.085f);\n            float rmy=Mathf.Max(iy+.035f,SampleTerrainY(terrain,rm.x,rm.y)+.085f),roy=Mathf.Max(iy+.05f,SampleTerrainY(terrain,ro.x,ro.y)+.085f);\n            verts.Add(new Vector3(lo.x,loy,lo.y));verts.Add(new Vector3(lm.x,lmy,lm.y));verts.Add(new Vector3(li.x,iy,li.y));\n            verts.Add(new Vector3(ri.x,iy,ri.y));verts.Add(new Vector3(rm.x,rmy,rm.y));verts.Add(new Vector3(ro.x,roy,ro.y));\n            float v=i*.045f; for(int k=0;k<6;k++)uvs.Add(new Vector2((k%3)*.5f,v));\n        }\n'''
new+='''        for(int i=0;i<segs;i++)\n        {\n            int a=i*6,na=a+6;\n            int[] q={0,1,1,2,3,4,4,5};\n            for(int j=0;j<q.Length;j+=2)\n            {\n                int u=a+q[j],v=a+q[j+1],nu=na+q[j],nv=na+q[j+1];\n                tris.Add(u);tris.Add(v);tris.Add(nu);tris.Add(v);tris.Add(nv);tris.Add(nu);\n            }\n        }\n        string path="Assets/World/NewSorpigal/Generated/RealRiverBanks.asset";\n        var mesh=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(!mesh){mesh=new Mesh();AssetDatabase.CreateAsset(mesh,path);}\n        mesh.Clear();mesh.indexFormat=IndexFormat.UInt32;mesh.SetVertices(verts);mesh.SetTriangles(tris,0);mesh.SetUVs(0,uvs);mesh.RecalculateNormals();mesh.RecalculateBounds();EditorUtility.SetDirty(mesh);\n        var go=new GameObject("River Banks - Natural Soil");go.transform.SetParent(parent);go.AddComponent<MeshFilter>().sharedMesh=mesh;\n        var mat=CreateSimpleMaterial("RiverBankSoil",Shader.Find("MMUnity/RiverBank"),new Color(.33f,.30f,.18f,1f));\n        mat.SetTexture("_MainTex",AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/EnvironmentAssets/UnitySamples/dry_soil_CH.png"));EditorUtility.SetDirty(mat);\n        var mr=go.AddComponent<MeshRenderer>();mr.sharedMaterial=mat;mr.shadowCastingMode=ShadowCastingMode.Off;mr.receiveShadows=true;return go;\n    }\n\n'''
s=s[:a]+new+s[b:]
p.write_text(s,encoding='utf-8')
print('RIVER_BANK_CONFORM_V7_PATCHED')
