using System;using System.IO;using System.Linq;using System.Text;using System.Collections.Generic;using System.Security.Cryptography;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/StructuralQA",Backup="Backups/StructuralCleanup_20260920";
 string Key(Transform t)=>t.parent?Key(t.parent)+"/"+t.GetSiblingIndex():t.GetSiblingIndex().ToString();
 string PathOf(Transform t)=>t.parent?PathOf(t.parent)+"/"+t.name:t.name;
 string Asset(UnityEngine.Object o){if(!o)return "null";return GlobalObjectId.GetGlobalObjectIdSlow(o).ToString()+"|"+AssetDatabase.GetAssetPath(o);}
 string Hash(string text){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(text))).Replace("-","");}
 HashSet<string> allowed=new HashSet<string>();
 string Snapshot(Scene s){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true))){string key=Key(t);rows.Add(key+"|"+(allowed.Contains(Key(t))?new Vector3(t.localPosition.x,0,t.localPosition.z):t.localPosition).ToString("R")+"|"+new Vector2(t.position.x,t.position.z).ToString("R")+"|"+t.localRotation.ToString("R")+"|"+t.localScale.ToString("R")+"|"+t.gameObject.activeSelf+"|"+GameObjectUtility.GetStaticEditorFlags(t.gameObject));foreach(var r in t.GetComponents<Renderer>()){rows.Add(key+"|R|"+r.GetType().Name+"|"+r.enabled+"|"+r.shadowCastingMode+"|"+r.receiveShadows+"|"+r.lightProbeUsage+"|"+r.reflectionProbeUsage+"|"+r.renderingLayerMask+"|"+string.Join(";",r.sharedMaterials.Select(m=>Asset(m)+"|instancing="+(m&&m.enableInstancing))));var sk=r as SkinnedMeshRenderer;if(sk)rows.Add(key+"|SK|"+Asset(sk.sharedMesh));}foreach(var m in t.GetComponents<MeshFilter>())rows.Add(key+"|M|"+Asset(m.sharedMesh));foreach(var l in t.GetComponents<LODGroup>())rows.Add(key+"|LOD|"+l.enabled+"|"+string.Join(";",l.GetLODs().Select(q=>q.screenRelativeTransitionHeight+":"+q.fadeTransitionWidth+":"+string.Join(",",q.renderers.Select(r=>r?Key(r.transform):"null")))));foreach(var td in t.GetComponents<Terrain>())rows.Add(key+"|TERRAIN|"+Asset(td.terrainData)+"|"+td.drawInstanced+"|"+td.heightmapPixelError);foreach(var c in t.GetComponents<Collider>())rows.Add(key+"|COLLIDER|"+c.GetType().Name+"|"+c.enabled+"|"+c.isTrigger);}return string.Join("\n",rows);}


Vector3 Parse(string s){var a=s.Trim('(',')').Split(',');return new Vector3(float.Parse(a[0],System.Globalization.CultureInfo.InvariantCulture),float.Parse(a[1],System.Globalization.CultureInfo.InvariantCulture),float.Parse(a[2],System.Globalization.CultureInfo.InvariantCulture));}
 bool Bad(Renderer r){var mf=r.GetComponent<MeshFilter>();var sk=r as SkinnedMeshRenderer;var mesh=mf?mf.sharedMesh:sk?sk.sharedMesh:null;string a=(r.name+"|"+(mesh?mesh.name:"")+"|"+AssetDatabase.GetAssetPath(mesh)+"|"+string.Join(";",r.sharedMaterials.Select(m=>AssetDatabase.GetAssetPath(m)))).ToLowerInvariant();return a.Contains("searsia_lucida")||a.Contains("pine_00")||a.Contains("pine_b")||a.Contains("pine_c")||a.Contains("pine_d")||a.Contains("banyantree")||a.Contains("tree_small_02_lod1");}

public void Execute(ExecutionResult result){
for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");var report=new List<string>{"scene,missing_prefabs,rejected_visible,broken_materials,open_errors,open_warnings,protected_state"};
foreach(var path in Directory.GetFiles("Assets/Scenes","*.unity",SearchOption.AllDirectories).Where(p=>!Path.GetFileName(p).StartsWith("_Recovery_")).OrderBy(p=>Path.GetFileName(p)=="Enroth.unity"?1:0).ThenBy(p=>p)){
int errors=0,warnings=0;Application.LogCallback cb=(m,st,t)=>{if(t==LogType.Warning)warnings++;if(t==LogType.Error||t==LogType.Exception||t==LogType.Assert)errors++;};Application.logMessageReceived+=cb;Scene s;try{s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);}finally{Application.logMessageReceived-=cb;}var ts=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var rs=ts.SelectMany(t=>t.GetComponents<Renderer>()).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();int missing=ts.Count(t=>PrefabUtility.GetPrefabInstanceStatus(t.gameObject)==PrefabInstanceStatus.MissingAsset),badCount=rs.Count(Bad),broken=rs.Count(r=>r.sharedMaterials.Any(m=>!m||!m.shader||!m.shader.isSupported||m.shader.name.Contains("InternalErrorShader")));
allowed.Clear();string state="PASS";
if(!s.name.Contains("Enroth_Linked")){if(s.name=="MireOfTheDamned"){var paths=File.ReadAllLines(Out+"/"+s.name+"_ground_corrections.txt").Select(l=>l.Split('|')[0]).ToArray();foreach(var t in ts.Where(t=>paths.Contains(PathOf(t))))allowed.Add(Key(t));}
var original=File.ReadAllLines(Out+"/"+s.name+"_after.txt");for(int j=0;j<original.Length;j++){var f=original[j].Split('|');if(f[1].StartsWith("(")){var local=Parse(f[1]);if(allowed.Contains(f[0]))local.y=0;var world=Parse(f[2]);f[1]=local.ToString("R");f[2]=new Vector2(world.x,world.z).ToString("R");original[j]=string.Join("|",f);}}
if(string.Join("\n",original)!=Snapshot(s)){state="FAIL";File.WriteAllText(Out+"/"+s.name+"_final_snapshot.txt",Snapshot(s));}
}
report.Add(s.name+","+missing+","+badCount+","+broken+","+errors+","+warnings+","+state);File.WriteAllLines(Out+"/final_audit.csv",report);if(missing+badCount+broken+errors+warnings>0||state=="FAIL")throw new Exception("Final check failed: "+report.Last());
if(s.name=="MireOfTheDamned"){var terrain=ts.Select(t=>t.GetComponent<Terrain>()).First(t=>t);foreach(string anchor in new[]{"Eco_GREEN_4_50","Eco_GREEN_8_34","SourceTree_0285_6tree13"}){var t=ts.First(a=>a.name==anchor);var target=t.position;target.y=terrain.SampleHeight(target)+terrain.transform.position.y+2;var go=new GameObject("QA Camera");var c=go.AddComponent<Camera>();c.farClipPlane=2000;c.fieldOfView=50;c.transform.position=target+new Vector3(12,5,-12);c.transform.LookAt(target);MMSequentialEvidence.Render(c,Out+"/grounded_"+anchor+".png",1000,800);UnityEngine.Object.DestroyImmediate(go);}}
if(s.name.Contains("Enroth_Linked")){var terrains=ts.Select(t=>t.GetComponent<Terrain>()).Where(t=>t).ToArray();float max=0;int pairs=0;foreach(var a in terrains)foreach(var b in terrains){var ap=a.transform.position;var bp=b.transform.position;int n=a.terrainData.heightmapResolution;if(Mathf.Abs(ap.x+a.terrainData.size.x-bp.x)<.001f&&Mathf.Abs(ap.z-bp.z)<.001f){pairs++;for(int k=0;k<n;k++)max=Mathf.Max(max,Mathf.Abs(ap.y+a.terrainData.GetHeight(n-1,k)-bp.y-b.terrainData.GetHeight(0,k)));}if(Mathf.Abs(ap.z+a.terrainData.size.z-bp.z)<.001f&&Mathf.Abs(ap.x-bp.x)<.001f){pairs++;for(int k=0;k<n;k++)max=Mathf.Max(max,Mathf.Abs(ap.y+a.terrainData.GetHeight(k,n-1)-bp.y-b.terrainData.GetHeight(k,0)));}}File.WriteAllText(Out+"/final_seams.txt","neighbor_pairs="+pairs+"\nmax_gap_m="+max+"\n");}
}
result.Log("16/16 + linked final verification PASS");}}
