using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 string PathOf(Transform t)=>t.parent?PathOf(t.parent)+"/"+t.name:t.name;
 bool Bad(Renderer r){var mf=r.GetComponent<MeshFilter>();var sk=r as SkinnedMeshRenderer;var mesh=mf?mf.sharedMesh:sk?sk.sharedMesh:null;string a=(r.name+"|"+(mesh?mesh.name:"")+"|"+AssetDatabase.GetAssetPath(mesh)+"|"+string.Join(";",r.sharedMaterials.Select(m=>AssetDatabase.GetAssetPath(m)))).ToLowerInvariant();return a.Contains("searsia_lucida")||a.Contains("pine_00")||a.Contains("pine_b")||a.Contains("pine_c")||a.Contains("pine_d")||a.Contains("banyantree")||a.Contains("tree_small_02_lod1");}
 public void Execute(ExecutionResult result){for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");var reports=new List<string>{"scene,missing_prefabs,rejected_visible,broken_material_renderers,approved_tree_ground_flags,approved_tree_tilt_flags,open_errors,open_warnings"};var details=new List<string>();var paths=Directory.GetFiles("Assets/Scenes","*.unity",SearchOption.AllDirectories).Where(p=>!Path.GetFileName(p).StartsWith("_Recovery_")).OrderBy(p=>Path.GetFileName(p)=="Enroth.unity"?1:0).ThenBy(p=>p).ToArray();
 foreach(var path in paths){int errors=0,warnings=0;Application.LogCallback callback=(msg,stack,type)=>{if(type==LogType.Warning)warnings++;if(type==LogType.Error||type==LogType.Exception||type==LogType.Assert)errors++;};Application.logMessageReceived+=callback;Scene s;try{s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);}finally{Application.logMessageReceived-=callback;}var ts=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var terrains=ts.Select(t=>t.GetComponent<Terrain>()).Where(t=>t).ToArray();var rs=ts.SelectMany(t=>t.GetComponents<Renderer>()).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();int missing=ts.Count(t=>PrefabUtility.GetPrefabInstanceStatus(t.gameObject)==PrefabInstanceStatus.MissingAsset),bad=rs.Count(Bad),broken=0,ground=0,tilt=0;
 foreach(var r in rs){if(r.sharedMaterials.Any(m=>!m||!m.shader||!m.shader.isSupported||m.shader.name.Contains("InternalErrorShader"))){broken++;details.Add(s.name+"|MATERIAL|"+PathOf(r.transform));}if(Bad(r))details.Add(s.name+"|REJECTED|"+PathOf(r.transform));}
 foreach(var t in ts.Where(t=>t.name.StartsWith("ApprovedReplacement_")&&t.gameObject.activeInHierarchy)){var vr=t.GetComponentsInChildren<Renderer>(true).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();if(vr.Length==0)continue;var p=t.position;var terrain=terrains.FirstOrDefault(a=>p.x>=a.transform.position.x&&p.z>=a.transform.position.z&&p.x<=a.transform.position.x+a.terrainData.size.x&&p.z<=a.transform.position.z+a.terrainData.size.z);if(!terrain)continue;float y=terrain.SampleHeight(p)+terrain.transform.position.y;float bottom=vr.Min(r=>r.bounds.min.y);if(Mathf.Abs(bottom-y)>.15f){ground++;details.Add(s.name+"|GROUND|"+PathOf(t)+"|gap="+(bottom-y));}if(Vector3.Dot(t.up,Vector3.up)<.98f){tilt++;details.Add(s.name+"|TILT|"+PathOf(t));}}
 reports.Add(s.name+","+missing+","+bad+","+broken+","+ground+","+tilt+","+errors+","+warnings);if(!s.name.Contains("Enroth_Linked"))MMSequentialEvidence.CaptureSorpigal(s,"structural_qa_"+s.name);
 else{var go=new GameObject("__StructuralQACamera");SceneManager.MoveGameObjectToScene(go,s);try{var c=go.AddComponent<Camera>();c.depthTextureMode=DepthTextureMode.Depth;c.farClipPlane=10000;c.orthographic=true;c.orthographicSize=1700;c.transform.position=new Vector3(-100,4000,0);c.transform.rotation=Quaternion.Euler(90,0,0);MMSequentialEvidence.Render(c,"Validation/StructuralQA/linked_overview.png",1600,1000);c.orthographic=false;c.fieldOfView=50;c.transform.position=new Vector3(-950,900,-1650);c.transform.LookAt(new Vector3(-100,0,0));MMSequentialEvidence.Render(c,"Validation/StructuralQA/linked_oblique.png",1600,1000);var ns=terrains.Single(t=>AssetDatabase.GetAssetPath(t.terrainData).Contains("NewSorpigal"));var center=ns.transform.position+new Vector3(306,25,226);c.transform.position=center+new Vector3(32,22,-38);c.transform.LookAt(center-Vector3.up*23);MMSequentialEvidence.Render(c,"Validation/StructuralQA/linked_sorpigal.png",1200,900);}finally{UnityEngine.Object.DestroyImmediate(go);}}
 File.WriteAllLines("Validation/StructuralQA/visual_audit.csv",reports);File.WriteAllLines("Validation/StructuralQA/visual_flags.txt",details);
 }
 result.Log("17 scenes inspected; linked open. See visual_audit.csv");
 }
}
