using System;using System.IO;using System.Linq;using System.Text;using System.Collections.Generic;using System.Security.Cryptography;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/StructuralQA",Backup="Backups/StructuralCleanup_20260920";
 string Key(Transform t)=>t.parent?Key(t.parent)+"/"+t.GetSiblingIndex():t.GetSiblingIndex().ToString();
 string PathOf(Transform t)=>t.parent?PathOf(t.parent)+"/"+t.name:t.name;
 string Asset(UnityEngine.Object o){if(!o)return "null";return GlobalObjectId.GetGlobalObjectIdSlow(o).ToString()+"|"+AssetDatabase.GetAssetPath(o);}
 string Hash(string text){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(text))).Replace("-","");}
 string Snapshot(Scene s){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true))){string key=Key(t);rows.Add(key+"|"+t.localPosition.ToString("R")+"|"+t.position.ToString("R")+"|"+t.localRotation.ToString("R")+"|"+t.localScale.ToString("R")+"|"+t.gameObject.activeSelf+"|"+GameObjectUtility.GetStaticEditorFlags(t.gameObject));foreach(var r in t.GetComponents<Renderer>()){rows.Add(key+"|R|"+r.GetType().Name+"|"+r.enabled+"|"+r.shadowCastingMode+"|"+r.receiveShadows+"|"+r.lightProbeUsage+"|"+r.reflectionProbeUsage+"|"+r.renderingLayerMask+"|"+string.Join(";",r.sharedMaterials.Select(m=>Asset(m)+"|instancing="+(m&&m.enableInstancing))));var sk=r as SkinnedMeshRenderer;if(sk)rows.Add(key+"|SK|"+Asset(sk.sharedMesh));}foreach(var m in t.GetComponents<MeshFilter>())rows.Add(key+"|M|"+Asset(m.sharedMesh));foreach(var l in t.GetComponents<LODGroup>())rows.Add(key+"|LOD|"+l.enabled+"|"+string.Join(";",l.GetLODs().Select(q=>q.screenRelativeTransitionHeight+":"+q.fadeTransitionWidth+":"+string.Join(",",q.renderers.Select(r=>r?Key(r.transform):"null")))));foreach(var td in t.GetComponents<Terrain>())rows.Add(key+"|TERRAIN|"+Asset(td.terrainData)+"|"+td.drawInstanced+"|"+td.heightmapPixelError);foreach(var c in t.GetComponents<Collider>())rows.Add(key+"|COLLIDER|"+c.GetType().Name+"|"+c.enabled+"|"+c.isTrigger);}return string.Join("\n",rows);}
 public void Execute(ExecutionResult result){for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene; not discarding");Directory.CreateDirectory(Out);string path=File.ReadAllText(Out+"/next.txt").Trim();string key=Path.GetFileNameWithoutExtension(path);if(File.Exists(Out+"/"+key+"_done.txt")){result.Log("Already processed");return;}var s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var all=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var missing=all.Where(t=>PrefabUtility.GetPrefabInstanceStatus(t.gameObject)==PrefabInstanceStatus.MissingAsset&&PrefabUtility.IsAnyPrefabInstanceRoot(t.gameObject)).ToArray();
 foreach(var t in missing){string p=PathOf(t).ToLowerInvariant();if(!p.Contains("tree")&&!p.Contains("vegetat")&&!p.Contains("forest")&&!p.Contains("shrub")&&!p.Contains("bush"))throw new Exception("Non-vegetation broken prefab requires separate review: "+p);}
 string before=Snapshot(s);File.WriteAllText(Out+"/"+key+"_before.txt",before);var anchorRows=new List<string>{"hierarchy_key|name|position|rotation|scale"};foreach(var t in missing)anchorRows.Add(Key(t)+"|"+t.name+"|"+t.position.ToString("R")+"|"+t.rotation.ToString("R")+"|"+t.lossyScale.ToString("R"));File.WriteAllLines(Out+"/"+key+"_anchors.txt",anchorRows);
 if(missing.Length>0){Directory.CreateDirectory(Backup);if(!File.Exists(Backup+"/"+Path.GetFileName(path)))File.Copy(path,Backup+"/"+Path.GetFileName(path));foreach(var t in missing)PrefabUtility.UnpackPrefabInstance(t.gameObject,PrefabUnpackMode.OutermostRoot,InteractionMode.AutomatedAction);if(Snapshot(s)!=before)throw new Exception("Unpack changed protected state; not saving");EditorSceneManager.MarkSceneDirty(s);if(!EditorSceneManager.SaveScene(s))throw new Exception("Save failed");}
 var messages=new List<string>();Application.LogCallback cb=(message,stack,type)=>{if(type==LogType.Error||type==LogType.Exception||type==LogType.Assert||type==LogType.Warning)messages.Add(type+"|"+message);};Application.logMessageReceived+=cb;try{s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);}finally{Application.logMessageReceived-=cb;}
 string after=Snapshot(s);File.WriteAllText(Out+"/"+key+"_after.txt",after);if(before!=after)throw new Exception("Saved/reloaded protected state mismatch");int remaining=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).Count(t=>PrefabUtility.GetPrefabInstanceStatus(t.gameObject)==PrefabInstanceStatus.MissingAsset);File.WriteAllLines(Out+"/"+key+"_open_messages.txt",messages);if(remaining>0||messages.Any(m=>m.ToLowerInvariant().Contains("missing prefab")))throw new Exception("Broken prefab remains");
 File.WriteAllText(Out+"/"+key+"_done.txt","converted_anchors="+missing.Length+"\nmissing_prefab_objects="+remaining+"\nhash_before="+Hash(before)+"\nhash_after="+Hash(after)+"\nreopen_warnings_errors="+messages.Count+"\n");result.Log(key+" converted="+missing.Length+" missing=0 protected_hash=PASS reopen_messages="+messages.Count);
 }
}
