using System;using System.IO;using System.Linq;using System.Text;using System.Collections.Generic;using System.Security.Cryptography;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/StructuralQA",Backup="Backups/StructuralCleanup_20260920";
 string Key(Transform t)=>t.parent?Key(t.parent)+"/"+t.GetSiblingIndex():t.GetSiblingIndex().ToString();
 string PathOf(Transform t)=>t.parent?PathOf(t.parent)+"/"+t.name:t.name;
 string Asset(UnityEngine.Object o){if(!o)return "null";return GlobalObjectId.GetGlobalObjectIdSlow(o).ToString()+"|"+AssetDatabase.GetAssetPath(o);}
 string Hash(string text){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(text))).Replace("-","");}
 HashSet<string> allowed=new HashSet<string>();
 string Snapshot(Scene s){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true))){string key=Key(t);rows.Add(key+"|"+(allowed.Contains(Key(t))?new Vector3(t.localPosition.x,0,t.localPosition.z):t.localPosition).ToString("R")+"|"+new Vector2(t.position.x,t.position.z).ToString("R")+"|"+t.localRotation.ToString("R")+"|"+t.localScale.ToString("R")+"|"+t.gameObject.activeSelf+"|"+GameObjectUtility.GetStaticEditorFlags(t.gameObject));foreach(var r in t.GetComponents<Renderer>()){rows.Add(key+"|R|"+r.GetType().Name+"|"+r.enabled+"|"+r.shadowCastingMode+"|"+r.receiveShadows+"|"+r.lightProbeUsage+"|"+r.reflectionProbeUsage+"|"+r.renderingLayerMask+"|"+string.Join(";",r.sharedMaterials.Select(m=>Asset(m)+"|instancing="+(m&&m.enableInstancing))));var sk=r as SkinnedMeshRenderer;if(sk)rows.Add(key+"|SK|"+Asset(sk.sharedMesh));}foreach(var m in t.GetComponents<MeshFilter>())rows.Add(key+"|M|"+Asset(m.sharedMesh));foreach(var l in t.GetComponents<LODGroup>())rows.Add(key+"|LOD|"+l.enabled+"|"+string.Join(";",l.GetLODs().Select(q=>q.screenRelativeTransitionHeight+":"+q.fadeTransitionWidth+":"+string.Join(",",q.renderers.Select(r=>r?Key(r.transform):"null")))));foreach(var td in t.GetComponents<Terrain>())rows.Add(key+"|TERRAIN|"+Asset(td.terrainData)+"|"+td.drawInstanced+"|"+td.heightmapPixelError);foreach(var c in t.GetComponents<Collider>())rows.Add(key+"|COLLIDER|"+c.GetType().Name+"|"+c.enabled+"|"+c.isTrigger);}return string.Join("\n",rows);}


Vector3 Parse(string s){var a=s.Trim('(',')').Split(',');return new Vector3(float.Parse(a[0],System.Globalization.CultureInfo.InvariantCulture),float.Parse(a[1],System.Globalization.CultureInfo.InvariantCulture),float.Parse(a[2],System.Globalization.CultureInfo.InvariantCulture));}
public void Execute(ExecutionResult result){
EditorSceneManager.OpenScene("Assets/Scenes/Enroth_Linked_OpenWorld.unity",OpenSceneMode.Single);
var log=new List<string>();
foreach(string name in new[]{"Dragonsand_SourceGrid","Kriegspire_SourceGrid","NewSorpigal_OpenWorld","SweetWater_SourceGrid"}){var s=EditorSceneManager.OpenScene("Assets/Scenes/"+name+".unity",OpenSceneMode.Single);var ts=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var baseline=File.ReadAllLines(Out+"/"+name+"_after.txt").Where(l=>l.Split('|')[1].StartsWith("(")).ToDictionary(l=>l.Split('|')[0],l=>Parse(l.Split('|')[1]));var paths=File.ReadAllLines(Out+"/"+name+"_ground_corrections.txt").Select(l=>l.Split('|')[0]).ToArray();allowed.Clear();foreach(var t in ts.Where(t=>paths.Contains(PathOf(t))))allowed.Add(Key(t));string before=Snapshot(s);int count=0;foreach(var t in ts.Where(t=>paths.Contains(PathOf(t)))){t.localPosition=baseline[Key(t)];count++;}if(Snapshot(s)!=before)throw new Exception("Restoration invariant");EditorSceneManager.MarkSceneDirty(s);EditorSceneManager.SaveScene(s);log.Add(name+" restored unconfirmed candidates="+count);}
var mire=EditorSceneManager.OpenScene("Assets/Scenes/MireOfTheDamned_SourceGrid.unity",OpenSceneMode.Single);var mt=mire.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var changed=File.ReadAllLines(Out+"/MireOfTheDamned_SourceGrid_ground_corrections.txt").Select(l=>l.Split('|')[0]).ToArray();var positions=mt.Where(t=>changed.Contains(PathOf(t))).ToDictionary(t=>PathOf(t).Substring(PathOf(t).IndexOf('/')),t=>t.localPosition);
var linked=EditorSceneManager.OpenScene("Assets/Scenes/Enroth_Linked_OpenWorld.unity",OpenSceneMode.Single);var lt=linked.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).Where(t=>PathOf(t).Contains("Mire of the Damned")||PathOf(t).Contains("Mire Of The Damned")||PathOf(t).Contains("MireOfTheDamned")).ToArray();
var targets=new Dictionary<Transform,Vector3>();foreach(var t in lt){string p=PathOf(t);int idx=p.IndexOf('/');if(idx>=0&&positions.ContainsKey(p.Substring(idx)))targets[t]=positions[p.Substring(idx)];}
if(targets.Count!=positions.Count){File.WriteAllLines(Out+"/linked_roots.txt",linked.GetRootGameObjects().Select(g=>g.name));throw new Exception("Mire linked matching "+targets.Count+" expected "+positions.Count);}
allowed.Clear();foreach(var t in targets)allowed.Add(Key(t.Key));string lb=Snapshot(linked);foreach(var t in targets)t.Key.localPosition=t.Value;if(Snapshot(linked)!=lb)throw new Exception("Linked protected state mismatch");string bak=Backup+"/Enroth_Linked_OpenWorld.unity";if(!File.Exists(bak))File.Copy(linked.path,bak);EditorSceneManager.MarkSceneDirty(linked);EditorSceneManager.SaveScene(linked);linked=EditorSceneManager.OpenScene(linked.path,OpenSceneMode.Single);if(Snapshot(linked)!=lb)throw new Exception("Linked reload failed");log.Add("Mire grounded=50; linked matched=50; invariant=PASS");File.WriteAllLines(Out+"/final_grounding.txt",log);result.Log(string.Join("\n",log));}}
