using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/FloatingTreeCheck_20260920";
 string Key(Transform t)=>t.parent?Key(t.parent)+"/"+t.GetSiblingIndex():t.GetSiblingIndex().ToString();
 string P(Transform t)=>t.parent?P(t.parent)+"/"+t.name:t.name;
 string Asset(UnityEngine.Object o){if(!o)return "null";return GlobalObjectId.GetGlobalObjectIdSlow(o).ToString()+"|"+AssetDatabase.GetAssetPath(o);}
 string Disp(string scene){if(scene=="FrozenHighlands")return "White Cap / Frozen Highlands";if(scene=="Kriegspire")return "Kriegspire";if(scene=="SilverCove")return "Silver Cove";if(scene=="SweetWater")return "Sweet Water";throw new Exception("No display mapping "+scene);}
 HashSet<string> allowed=new HashSet<string>();
 string Snapshot(Scene s){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true))){string k=Key(t);Vector3 lp=t.localPosition;if(allowed.Contains(k))lp.y=0;rows.Add(k+"|"+lp.ToString("R")+"|"+t.localRotation.ToString("R")+"|"+t.localScale.ToString("R")+"|"+t.gameObject.activeSelf);foreach(var r in t.GetComponents<Renderer>())rows.Add(k+"|R|"+r.enabled+"|"+r.shadowCastingMode+"|"+string.Join(";",r.sharedMaterials.Select(m=>Asset(m)+"|inst="+(m&&m.enableInstancing))));foreach(var mf in t.GetComponents<MeshFilter>())rows.Add(k+"|M|"+Asset(mf.sharedMesh));}return string.Join("\n",rows);}
 string Rel(Transform t,Transform root){var p=P(t);var rp=P(root);if(!p.StartsWith(rp+"/"))throw new Exception("Relative path failed");return p.Substring(rp.Length+1);}
 public void Execute(ExecutionResult result){
  var selected=File.ReadAllLines(Out+"/floating_selected.tsv").Select(l=>l.Split('\t')).Where(p=>p.Length>=3).ToArray();
  var sourceLocalY=new Dictionary<string,float>();
  foreach(var grp in selected.GroupBy(p=>p[0])){string sp="Assets/Scenes/"+grp.Key+".unity";var ss=EditorSceneManager.OpenScene(sp,OpenSceneMode.Single);var root=ss.GetRootGameObjects().First(g=>g.name.IndexOf("Open World",StringComparison.OrdinalIgnoreCase)>=0).transform;var all=ss.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();foreach(var row in grp){var mm=all.Where(t=>P(t)==row[1]).ToArray();if(mm.Length!=1)throw new Exception("Source match "+mm.Length+" "+row[1]);string rel=Rel(mm[0],root);sourceLocalY[grp.Key+"|"+rel]=mm[0].localPosition.y;}}
  var linked=EditorSceneManager.OpenScene("Assets/Scenes/World/Enroth.unity",OpenSceneMode.Single);var lt=linked.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();var targets=new List<System.Tuple<Transform,float,string>>();
  foreach(var row in selected){string disp=Disp(row[0]);var roots=lt.Where(t=>t.name.StartsWith(disp+" - LINKED",StringComparison.OrdinalIgnoreCase)).ToArray();if(roots.Length!=1)throw new Exception("Linked region roots "+roots.Length+" "+disp);var root=roots[0];string sourceRoot=row[1].Substring(0,row[1].IndexOf('/'));string rel=row[1].Substring(sourceRoot.Length+1);var mm=root.GetComponentsInChildren<Transform>(true).Where(t=>t!=root&&Rel(t,root)==rel).ToArray();if(mm.Length!=1)throw new Exception("Linked match "+mm.Length+" "+disp+" "+rel);targets.Add(System.Tuple.Create(mm[0],sourceLocalY[row[0]+"|"+rel],row[0]+"|"+rel));}
  allowed.Clear();foreach(var x in targets)allowed.Add(Key(x.Item1));string before=Snapshot(linked);var logs=new List<string>();foreach(var x in targets){var t=x.Item1;var lp=t.localPosition;var rot=t.localRotation;var sc=t.localScale;t.localPosition=new Vector3(lp.x,x.Item2,lp.z);if(t.localPosition.x!=lp.x||t.localPosition.z!=lp.z||t.localRotation!=rot||t.localScale!=sc)throw new Exception("Non-Y linked change "+x.Item3);logs.Add(x.Item3+"|oldLocalY="+lp.y.ToString("R")+"|newLocalY="+t.localPosition.y.ToString("R"));}
  if(Snapshot(linked)!=before)throw new Exception("Linked protected state changed");EditorSceneManager.MarkSceneDirty(linked);if(!EditorSceneManager.SaveScene(linked))throw new Exception("Linked save failed");linked=EditorSceneManager.OpenScene(linked.path,OpenSceneMode.Single);if(Snapshot(linked)!=before)throw new Exception("Linked reload invariant");File.WriteAllLines(Out+"/linked_y_sync.txt",logs);File.WriteAllText(Out+"/FINAL_TREE_GROUNDING.txt","standalone_fixed=21\nlinked_synced=21\nonly_y_changed=PASS\norientation_unchanged=PASS\nscale_unchanged=PASS\nxz_unchanged=PASS\nmeshes_materials_unchanged=PASS\n");result.Log("Linked Y sync=21 onlyY=PASS");
 }
}