using System;using System.IO;using System.Linq;using System.Text;using System.Collections.Generic;using System.Security.Cryptography;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/VisualRefinement",Backup="Backups/VisualRefinement_20260920";
 string Key(Transform t)=>t.parent?Key(t.parent)+"/"+t.GetSiblingIndex():t.GetSiblingIndex().ToString();
 string PathOf(Transform t)=>t.parent?PathOf(t.parent)+"/"+t.name:t.name;
 string Asset(UnityEngine.Object o){if(!o)return "null";return GlobalObjectId.GetGlobalObjectIdSlow(o).ToString()+"|"+AssetDatabase.GetAssetPath(o);}
 string Hash(string text){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(text))).Replace("-","");}
 HashSet<string> materialTargets=new HashSet<string>();
 string Snapshot(Scene s){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true))){string key=Key(t);rows.Add(key+"|"+t.localPosition.ToString("R")+"|"+t.position.ToString("R")+"|"+t.localRotation.ToString("R")+"|"+t.localScale.ToString("R")+"|"+t.gameObject.activeSelf+"|"+GameObjectUtility.GetStaticEditorFlags(t.gameObject));foreach(var r in t.GetComponents<Renderer>()){rows.Add(key+"|R|"+r.GetType().Name+"|"+r.enabled+"|"+r.shadowCastingMode+"|"+r.receiveShadows+"|"+r.lightProbeUsage+"|"+r.reflectionProbeUsage+"|"+r.renderingLayerMask+"|"+string.Join(";",r.sharedMaterials.Select(m=>(materialTargets.Contains(key)?"approved-material":Asset(m))+"|instancing="+(m&&m.enableInstancing))));var sk=r as SkinnedMeshRenderer;if(sk)rows.Add(key+"|SK|"+Asset(sk.sharedMesh));}foreach(var m in t.GetComponents<MeshFilter>())rows.Add(key+"|M|"+Asset(m.sharedMesh));foreach(var l in t.GetComponents<LODGroup>())rows.Add(key+"|LOD|"+l.enabled+"|"+string.Join(";",l.GetLODs().Select(q=>q.screenRelativeTransitionHeight+":"+q.fadeTransitionWidth+":"+string.Join(",",q.renderers.Select(r=>r?Key(r.transform):"null")))));foreach(var td in t.GetComponents<Terrain>())rows.Add(key+"|TERRAIN|"+Asset(td.terrainData)+"|"+td.drawInstanced+"|"+td.heightmapPixelError);foreach(var c in t.GetComponents<Collider>())rows.Add(key+"|COLLIDER|"+c.GetType().Name+"|"+c.enabled+"|"+c.isTrigger);}return string.Join("\n",rows);}


void Capture(Renderer r,string name){var b=r.bounds;var go=new GameObject("__LinkedVisualQA");var c=go.AddComponent<Camera>();c.fieldOfView=50;c.transform.position=b.center+new Vector3(b.size.y*.7f,0,-b.size.y*.8f);c.transform.LookAt(b.center);MMSequentialEvidence.Render(c,Out+"/"+name+".png",900,900);UnityEngine.Object.DestroyImmediate(go);}
public void Execute(ExecutionResult result){for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");var s=EditorSceneManager.OpenScene("Assets/Scenes/World/Enroth.unity",OpenSceneMode.Single);var rs=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).ToArray();var fixes=new Dictionary<Renderer,Material[]>();var rows=new Dictionary<string,string>();foreach(var file in Directory.GetFiles(Out,"*_material_changes.txt"))foreach(var line in File.ReadAllLines(file)){var parts=line.Split('|');rows[parts[0]]=parts[1];}
foreach(var row in rows){int idx=row.Key.IndexOf('/');string root=row.Key.Substring(0,idx).Split(new[]{" - "},StringSplitOptions.None)[0];string relative=row.Key.Substring(idx);var match=rs.Where(r=>PathOf(r.transform).IndexOf("/"+root+" - ",StringComparison.OrdinalIgnoreCase)>=0&&PathOf(r.transform).EndsWith(relative,StringComparison.Ordinal)).ToArray();if(match.Length!=1)throw new Exception("Linked matching="+match.Length+" "+row.Key);var mats=row.Value.Split(';').Select(p=>AssetDatabase.LoadAssetAtPath<Material>(p)).ToArray();if(mats.Any(m=>!m||!m.enableInstancing))throw new Exception("Invalid material");fixes[match[0]]=mats;materialTargets.Add(Key(match[0].transform));}
var pine=fixes.Keys.FirstOrDefault(r=>r.name=="Pine_A_LOD0"&&PathOf(r.transform).Contains("Bootleg"));var dead=fixes.Keys.FirstOrDefault(r=>r.name=="PineDead_03_LOD0"&&PathOf(r.transform).Contains("Sweet"));if(pine)Capture(pine,"linked_pine_before");if(dead)Capture(dead,"linked_dead_before");string before=Snapshot(s);File.WriteAllText(Out+"/linked_protected_before.txt",before);foreach(var fix in fixes)fix.Key.sharedMaterials=fix.Value;if(Snapshot(s)!=before)throw new Exception("Linked invariant failed");Directory.CreateDirectory(Backup);if(!File.Exists(Backup+"/Enroth.unity"))File.Copy(s.path,Backup+"/Enroth.unity");EditorSceneManager.MarkSceneDirty(s);EditorSceneManager.SaveScene(s);if(pine)Capture(pine,"linked_pine_after");if(dead)Capture(dead,"linked_dead_after");s=EditorSceneManager.OpenScene(s.path,OpenSceneMode.Single);if(Snapshot(s)!=before)throw new Exception("Linked reload failed");int parity=0;rs=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).ToArray();foreach(var row in rows){int idx=row.Key.IndexOf('/');string root=row.Key.Substring(0,idx).Split(new[]{" - "},StringSplitOptions.None)[0];string relative=row.Key.Substring(idx);var r=rs.Single(a=>PathOf(a.transform).IndexOf("/"+root+" - ",StringComparison.OrdinalIgnoreCase)>=0&&PathOf(a.transform).EndsWith(relative,StringComparison.Ordinal));if(string.Join(";",r.sharedMaterials.Select(m=>AssetDatabase.GetAssetPath(m)))!=row.Value)throw new Exception("Material parity failed");parity++;}File.WriteAllText(Out+"/linked_done.txt","matched_renderers="+parity+"\nprotected_hash="+Hash(before)+"\nprotected_state=PASS\nmaterial_parity=PASS\n");result.Log("Linked material parity="+parity+" protected state PASS");}}
