using System;using System.IO;using System.Linq;using System.Text;using System.Collections.Generic;using System.Security.Cryptography;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/VisualRefinement",Backup="Backups/VisualRefinement_20260920";
 string Key(Transform t)=>t.parent?Key(t.parent)+"/"+t.GetSiblingIndex():t.GetSiblingIndex().ToString();
 string PathOf(Transform t)=>t.parent?PathOf(t.parent)+"/"+t.name:t.name;
 string Asset(UnityEngine.Object o){if(!o)return "null";return GlobalObjectId.GetGlobalObjectIdSlow(o).ToString()+"|"+AssetDatabase.GetAssetPath(o);}
 string Hash(string text){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(text))).Replace("-","");}
 HashSet<string> materialTargets=new HashSet<string>();
 string Snapshot(Scene s){var rows=new List<string>();foreach(var t in s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true))){string key=Key(t);rows.Add(key+"|"+t.localPosition.ToString("R")+"|"+t.position.ToString("R")+"|"+t.localRotation.ToString("R")+"|"+t.localScale.ToString("R")+"|"+t.gameObject.activeSelf+"|"+GameObjectUtility.GetStaticEditorFlags(t.gameObject));foreach(var r in t.GetComponents<Renderer>()){rows.Add(key+"|R|"+r.GetType().Name+"|"+r.enabled+"|"+r.shadowCastingMode+"|"+r.receiveShadows+"|"+r.lightProbeUsage+"|"+r.reflectionProbeUsage+"|"+r.renderingLayerMask+"|"+string.Join(";",r.sharedMaterials.Select(m=>(materialTargets.Contains(key)?"approved-material":Asset(m))+"|instancing="+(m&&m.enableInstancing))));var sk=r as SkinnedMeshRenderer;if(sk)rows.Add(key+"|SK|"+Asset(sk.sharedMesh));}foreach(var m in t.GetComponents<MeshFilter>())rows.Add(key+"|M|"+Asset(m.sharedMesh));foreach(var l in t.GetComponents<LODGroup>())rows.Add(key+"|LOD|"+l.enabled+"|"+string.Join(";",l.GetLODs().Select(q=>q.screenRelativeTransitionHeight+":"+q.fadeTransitionWidth+":"+string.Join(",",q.renderers.Select(r=>r?Key(r.transform):"null")))));foreach(var td in t.GetComponents<Terrain>())rows.Add(key+"|TERRAIN|"+Asset(td.terrainData)+"|"+td.drawInstanced+"|"+td.heightmapPixelError);foreach(var c in t.GetComponents<Collider>())rows.Add(key+"|COLLIDER|"+c.GetType().Name+"|"+c.enabled+"|"+c.isTrigger);}return string.Join("\n",rows);}

public void Execute(ExecutionResult result){for(int i=0;i<SceneManager.sceneCount;i++)if(SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");string path=File.ReadAllText(Out+"/next.txt").Trim();var s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);var rs=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).Where(r=>r.enabled&&r.gameObject.activeInHierarchy).ToArray();var fixes=new Dictionary<Renderer,Material[]>();foreach(var r in rs.Where(r=>s.name!="NewSorpigal")){var f=r.GetComponent<MeshFilter>();if(!f||!f.sharedMesh)continue;if(r.name.StartsWith("Pine_A_LOD")&&r.sharedMaterials.All(m=>m&&m.name=="TreeBark")){var model=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/TerrainDemoScene_HDRP/Prefabs/Trees/Pines/Pine_A/Pine_A.st");var source=model.GetComponentsInChildren<Renderer>(true).First(a=>a.name==r.name);var mats=source.sharedMaterials.Select(m=>AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/VisualRefinement/"+(m.name.ToLowerInvariant().Contains("bark")?"PineA_Bark":m.name.Contains("Billboard")?"PineA_Billboard":"PineA_Foliage")+".mat")).ToArray();if(mats.Any(m=>!m||!m.mainTexture||!m.enableInstancing)||mats.Length!=f.sharedMesh.subMeshCount)throw new Exception("Pine A mapping invalid");fixes[r]=mats;materialTargets.Add(Key(r.transform));continue;}if(r.bounds.size.y<.4f)continue;string family=f.sharedMesh.name.Contains("island_tree_02")?"island_tree_02":f.sharedMesh.name.Contains("island_tree_01")?"island_tree_01":null;if(family==null||!r.sharedMaterials.Any(m=>AssetDatabase.GetAssetPath(m).StartsWith("Assets/Materials/RealisticWorld/IslandTree")))continue;var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Environment/FinalWorldVegetation/"+family+".prefab");var approved=prefab.GetComponentsInChildren<Renderer>(true).First(a=>a.enabled);if(approved.sharedMaterials.Length!=f.sharedMesh.subMeshCount)throw new Exception("Submesh mismatch");foreach(var m in approved.sharedMaterials)if(!m||!m.mainTexture||!m.enableInstancing||!m.shader.isSupported)throw new Exception("Approved material invalid");fixes[r]=approved.sharedMaterials;materialTargets.Add(Key(r.transform));}
string before=Snapshot(s);File.WriteAllText(Out+"/"+s.name+"_protected_before.txt",before);var rows=new List<string>();foreach(var fix in fixes){rows.Add(PathOf(fix.Key.transform)+"|"+string.Join(";",fix.Value.Select(m=>AssetDatabase.GetAssetPath(m))));fix.Key.sharedMaterials=fix.Value;}if(Snapshot(s)!=before)throw new Exception("Protected state changed");if(fixes.Count>0){Directory.CreateDirectory(Backup);if(!File.Exists(Backup+"/"+Path.GetFileName(path)))File.Copy(path,Backup+"/"+Path.GetFileName(path));EditorSceneManager.MarkSceneDirty(s);EditorSceneManager.SaveScene(s);s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);if(Snapshot(s)!=before)throw new Exception("Reload mismatch");}File.WriteAllLines(Out+"/"+s.name+"_material_changes.txt",rows);File.WriteAllText(Out+"/"+s.name+"_done.txt","corrected_material_renderers="+fixes.Count+"\nprotected_hash="+Hash(before)+"\nprotected_state=PASS\n");result.Log(s.name+" materials corrected="+fixes.Count+" protected state PASS");}}
