using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;
internal class CommandScript:IRunCommand{
 const string Out="Validation/FinalWorld", Backup="Backups/Coast17_20260919/WaterMeshes"; const float Water=.12f, MaxMove=.28f;
 struct K:IEquatable<K>{public int x,y,z;public K(Vector3 v){x=Mathf.RoundToInt(v.x*1000);y=Mathf.RoundToInt(v.y*1000);z=Mathf.RoundToInt(v.z*1000);}public bool Equals(K o)=>x==o.x&&y==o.y&&z==o.z;public override bool Equals(object o)=>o is K&&Equals((K)o);public override int GetHashCode()=>((x*397)^y)*397^z;}
 struct E:IEquatable<E>{public K a,b;public E(K x,K y){if(Cmp(x,y)<=0){a=x;b=y;}else{a=y;b=x;}}static int Cmp(K p,K q){int c=p.x.CompareTo(q.x);if(c!=0)return c;c=p.y.CompareTo(q.y);return c!=0?c:p.z.CompareTo(q.z);}public bool Equals(E o)=>a.Equals(o.a)&&b.Equals(o.b);public override bool Equals(object o)=>o is E&&Equals((E)o);public override int GetHashCode()=>a.GetHashCode()*397^b.GetHashCode();}
 bool IsWaterName(string n)=>n.StartsWith("Water -")||n=="Internal Water - Smooth"||n=="Unified Water Bottom"||n.StartsWith("Curved Seabed")||n=="Global Ocean Surface"||n=="Ocean + Central Lake Water";
 long Tris(UnityEngine.Mesh m){long n=0;for(int s=0;s<m.subMeshCount;s++)n+=m.GetIndexCount(s)/3;return n;}
 public void Execute(ExecutionResult result){
  string sp=File.ReadAllText(Out+"/next_water.txt").Trim(), key=Path.GetFileNameWithoutExtension(sp);if(File.Exists(Out+"/"+key+"_wateredge_done.txt")){result.Log("Already done");return;}
  var s=EditorSceneManager.OpenScene(sp,OpenSceneMode.Single);var terrain=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Terrain>(true)).Single();var wr=s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Renderer>(true)).FirstOrDefault(r=>r.name.StartsWith("Water -"));if(!wr){File.WriteAllText(Out+"/"+key+"_wateredge_done.txt","no_primary_water_renderer=1\n");result.Log(key+" no primary water");return;}var mf=wr.GetComponent<MeshFilter>();if(!mf||!mf.sharedMesh)throw new Exception("Water mesh missing");var m=mf.sharedMesh;long beforeTri=Tris(m);if(beforeTri==0){File.WriteAllText(Out+"/"+key+"_wateredge_done.txt","triangles=0\n");result.Log(key+" zero water tris");return;}
  string ap=AssetDatabase.GetAssetPath(m);Directory.CreateDirectory(Backup);string bp=Backup+"/"+key+"_WaterSurface.asset";if(!File.Exists(bp))File.Copy(ap,bp);
  var v=m.vertices;var original=(Vector3[])v.Clone();var groups=new Dictionary<K,List<int>>();for(int i=0;i<v.Length;i++){var k=new K(v[i]);if(!groups.TryGetValue(k,out var li))groups[k]=li=new List<int>();li.Add(i);}
  var ec=new Dictionary<E,int>();for(int sm=0;sm<m.subMeshCount;sm++){var ix=m.GetIndices(sm);for(int i=0;i+2<ix.Length;i+=3){K a=new K(v[ix[i]]),b=new K(v[ix[i+1]]),c=new K(v[ix[i+2]]);var es=new[]{new E(a,b),new E(b,c),new E(c,a)};foreach(var e in es)ec[e]=ec.TryGetValue(e,out var n)?n+1:1;}}
  var adj=new Dictionary<K,List<K>>();foreach(var kv in ec)if(kv.Value==1){if(!adj.TryGetValue(kv.Key.a,out var aa))adj[kv.Key.a]=aa=new List<K>();if(!adj.TryGetValue(kv.Key.b,out var bb))adj[kv.Key.b]=bb=new List<K>();aa.Add(kv.Key.b);bb.Add(kv.Key.a);}
  int moved=0,rejectDry=0,skipBorder=0,skipTopology=0;float max=0;var changes=new Dictionary<K,Vector3>();float size=terrain.terrainData.size.x;
  foreach(var kv in adj){K k=kv.Key;if(kv.Value.Count!=2||!groups.TryGetValue(k,out var ids)){skipTopology++;continue;}Vector3 cur=v[ids[0]],world=wr.transform.TransformPoint(cur);Vector3 localTerrain=world-terrain.transform.position;if(localTerrain.x<1.01f||localTerrain.z<1.01f||localTerrain.x>terrain.terrainData.size.x-1.01f||localTerrain.z>terrain.terrainData.size.z-1.01f){skipBorder++;continue;}var ns=kv.Value.ToArray();if(!groups.TryGetValue(ns[0],out var ia)||!groups.TryGetValue(ns[1],out var ib))continue;Vector3 target=(v[ia[0]]+v[ib[0]])*.5f;Vector3 delta=target-cur;delta.y=0;if(delta.sqrMagnitude<.000001f)continue;float d=delta.magnitude;if(d>MaxMove)delta*=MaxMove/d;Vector3 cand=cur+delta,worldCand=wr.transform.TransformPoint(cand);float th=terrain.SampleHeight(worldCand)+terrain.transform.position.y;if(th>Water+.03f){rejectDry++;continue;}changes[k]=cand;max=Mathf.Max(max,delta.magnitude);}
  foreach(var ch in changes){foreach(int i in groups[ch.Key]){v[i].x=ch.Value.x;v[i].z=ch.Value.z;}moved++;}
  m.vertices=v;m.RecalculateBounds();EditorUtility.SetDirty(m);AssetDatabase.SaveAssetIfDirty(m);if(Tris(m)!=beforeTri)throw new Exception("Triangle count changed");for(int i=0;i<v.Length;i++)if(Mathf.Abs(v[i].y-original[i].y)>.000001f)throw new Exception("Water Y changed");
  Directory.CreateDirectory(Out);File.WriteAllText(Out+"/"+key+"_wateredge_done.txt","mesh="+ap+"\ntriangles="+beforeTri+"\nboundary_position_groups="+adj.Count+"\nmoved_groups="+moved+"\nmax_move_m="+max+"\nrejected_dry="+rejectDry+"\nskipped_region_border="+skipBorder+"\nskipped_topology="+skipTopology+"\ntriangles_added=0\nwater_y_changes=0\n");
  result.Log(key+" water boundary moved="+moved+" max="+max+" dryReject="+rejectDry+" borderLocked="+skipBorder);
 }
}